import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { WorkspaceContext } from '../../platform/workspace/context'
import { WorkspaceShell } from '../../platform/ui/WorkspaceShell'
import { PanelShell } from '../../platform/ui/PanelShell'
import { Badge, Banner, Button, DefinitionList, EmptyValue, StatusBadge } from '../../platform/ui/primitives'
import { ErrorNotice, EmptyState } from '../../platform/ui/Notice'
import type { TeamRead } from '../../generated/schema'

type Member={user_id:string;role:string}
type Flag={key:string;enabled:boolean;description:string;rules:Record<string,unknown>;revision:number;updated_by:string;updated_at:string}
type Job={id:string;job_type:string;status:string;attempts:number;max_attempts:number;created_by:string;created_at:string;error:string|null}
type Notification={id:string;kind:string;title:string;body:string;read_at:string|null;created_at:string}
type NotificationPreference={user_id:string;kind:string;enabled:boolean;revision:number;updated_at:string}
type Hook={id:string;name:string;url:string;topics:string[];secret_ref:string;enabled:boolean;revision:number}
type Delivery={id:string;event_id:string;status:string;attempts:number;response_status:number|null;response_summary:string|null;last_error:string|null;created_at:string;updated_at:string}
type Audit={id:string;actor:string;workspace:string;entity_id:string;action:string;revision:number;request_id:string;created_at:string}
type Diagnostics={environment:string;profile:string;deployment_id:string;instance_id:string;webhook_allowed_hosts:number;docs_enabled:boolean}
type Tab='overview'|'members'|'teams'|'flags'|'jobs'|'notifications'|'webhooks'|'audit'

export function Workspace({api,permissions,user,tenant}:WorkspaceContext){
 const admin=permissions.includes('admin'),client=useQueryClient();const[tab,setTab]=useState<Tab>('overview')
 const diagnostics=useQuery({queryKey:['system','diagnostics',tenant],queryFn:()=>api.request<Diagnostics>('/api/v1/runtime-diagnostics'),enabled:admin})
 const notifications=useQuery({queryKey:['system','notifications',tenant,user],queryFn:()=>api.request<Notification[]>('/api/v1/notifications')})
 const tabs=useMemo(()=>[{id:'overview',label:'Overview'},...(admin?[{id:'members',label:'Members'},{id:'teams',label:'Teams'},{id:'flags',label:'Feature flags'},{id:'jobs',label:'Jobs'},{id:'webhooks',label:'Webhooks'},{id:'audit',label:'Audit'}]:[]),{id:'notifications',label:'Notifications'}] as Array<{id:Tab;label:string}>,[admin])
 return <WorkspaceShell eyebrow="Platform operations" title="System workspace" description="Tenant administration, diagnostics, integrations and private notifications use the same bounded API/security contracts as application data." commandBar={<div className="ui-toggle-group" role="tablist" aria-label="System sections">{tabs.map(item=><button key={item.id} role="tab" aria-selected={tab===item.id} className={tab===item.id?'active':''} onClick={()=>setTab(item.id)}>{item.label}</button>)}</div>}>
  {!admin&&<Banner title="Member administration is hidden" tone="info">Your role can use private notifications; administration requires the server-side admin permission.</Banner>}
  {tab==='overview'&&<Overview diagnostics={diagnostics.data} notificationCount={notifications.data?.filter(row=>!row.read_at).length??0} admin={admin}/>}
  {tab==='members'&&admin&&<Members api={api} tenant={tenant} invalidate={()=>void client.invalidateQueries({queryKey:['system','members',tenant]})}/>}
  {tab==='teams'&&admin&&<Teams api={api} tenant={tenant}/>}
  {tab==='flags'&&admin&&<Flags api={api} tenant={tenant}/>}
  {tab==='jobs'&&admin&&<Jobs api={api} tenant={tenant}/>}
  {tab==='notifications'&&<Notifications api={api} rows={notifications.data} error={notifications.error} refresh={()=>void client.invalidateQueries({queryKey:['system','notifications',tenant,user]})}/>}
  {tab==='webhooks'&&admin&&<Webhooks api={api} tenant={tenant}/>}
  {tab==='audit'&&admin&&<AuditLog api={api} tenant={tenant}/>}
 </WorkspaceShell>
}
function Overview({diagnostics,notificationCount,admin}:{diagnostics?:Diagnostics;notificationCount:number;admin:boolean}){return <div className="system-overview-grid"><PanelShell title="Runtime" subtitle="Safe deployment observations"><DefinitionList items={diagnostics?[{label:'Environment',value:diagnostics.environment},{label:'Profile',value:diagnostics.profile},{label:'Deployment',value:diagnostics.deployment_id},{label:'Webhook allowlist',value:diagnostics.webhook_allowed_hosts}]:[{label:'Diagnostics',value:admin?'Loading…':'Admin only'}]}/></PanelShell><PanelShell title="Operator boundary" subtitle="Production remains fail-closed"><div className="lab-stack"><StatusBadge status={admin?'Admin':'Read only'}/><Badge tone={notificationCount?'accent':'neutral'}>{notificationCount} unread notifications</Badge><p className="muted">Company identity/storage qualification is deployment evidence and cannot be inferred from this UI.</p></div></PanelShell><PanelShell title="Durable platform services" subtitle="SQLite-backed tenant infrastructure"><div className="capability-chips">{['Jobs','Events','Notifications','Feature flags','Webhooks','Audit','Backup/restore'].map(item=><span key={item}>{item}</span>)}</div></PanelShell></div>}
function Members({api,tenant,invalidate}:{api:WorkspaceContext['api'];tenant:string;invalidate:()=>void}){const query=useQuery({queryKey:['system','members',tenant],queryFn:()=>api.request<Member[]>('/api/v1/admin/members')});const[userId,setUserId]=useState(''),[role,setRole]=useState('editor'),[error,setError]=useState<unknown>(null);const save=async()=>{setError(null);try{await api.json('/api/v1/admin/members','POST',{user_id:userId,role});setUserId('');invalidate()}catch(e){setError(e)}};const change=async(row:Member,next:string)=>{setError(null);try{await api.json(`/api/v1/admin/members/${encodeURIComponent(row.user_id)}`,'PUT',{user_id:row.user_id,role:next});invalidate()}catch(e){setError(e)}};const remove=async(row:Member)=>{setError(null);try{await api.json(`/api/v1/admin/members/${encodeURIComponent(row.user_id)}`,'DELETE');invalidate()}catch(e){setError(e)}};return <PanelShell title="Members & roles" subtitle="Server-enforced roles with last-admin protection">{query.isError&&<ErrorNotice error={query.error}/>} {error!==null&&<ErrorNotice error={error}/>}<div className="system-inline-form"><input value={userId} maxLength={200} placeholder="user.name" onChange={e=>setUserId(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>editor</option><option>admin</option></select><Button disabled={!userId.trim()} onClick={()=>void save()}>Add member</Button></div><div className="system-list">{query.data?.map(row=><article key={row.user_id}><strong>{row.user_id}</strong><select value={row.role} onChange={e=>void change(row,e.target.value)}><option>viewer</option><option>editor</option><option>admin</option></select><Button tone="danger" size="sm" onClick={()=>void remove(row)}>Remove</Button></article>)}</div></PanelShell>}
function Teams({api,tenant}:{api:WorkspaceContext['api'];tenant:string}){
 const query=useQuery({queryKey:['system','teams',tenant],queryFn:()=>api.request<TeamRead[]>('/api/v1/teams')})
 const [name,setName]=useState(''),[slug,setSlug]=useState(''),[error,setError]=useState<unknown>(null),[member,setMember]=useState<Record<string,string>>({})
 const create=async()=>{setError(null);try{await api.json<TeamRead>('/api/v1/teams','POST',{name,slug});setName('');setSlug('');await query.refetch()}catch(e){setError(e)}}
 const add=async(team:TeamRead)=>{const user_id=(member[team.id]??'').trim();if(!user_id)return;setError(null);try{await api.json(`/api/v1/teams/${encodeURIComponent(team.id)}/members`,'POST',{user_id,role:'member'});setMember(current=>({...current,[team.id]:''}));await query.refetch()}catch(e){setError(e)}}
 return <PanelShell title="Workspace teams" subtitle="Membership-scoped saved-view ownership"><p className="muted">Default workspace membership follows the tenant; named teams are explicit server-enforced scopes for shared views.</p>{query.isError&&<ErrorNotice error={query.error}/>} {error!==null&&<ErrorNotice error={error}/>}<div className="system-inline-form"><input aria-label="Team name" value={name} maxLength={120} placeholder="Platform team" onChange={event=>setName(event.target.value)}/><input aria-label="Team slug" value={slug} maxLength={80} placeholder="platform-team" onChange={event=>setSlug(event.target.value)}/><Button disabled={!name.trim()||!/^[a-z][a-z0-9-]{1,79}$/.test(slug)} onClick={()=>void create()}>Create team</Button></div><div className="system-list">{query.data?.map(team=><article key={team.id}><div><strong>{team.name}</strong><small>{team.slug} · {team.member_count} explicit members{team.is_default?' · default':''}</small></div>{!team.is_default&&<><input aria-label={`Add member to ${team.name}`} value={member[team.id]??''} placeholder="user.name" onChange={event=>setMember(current=>({...current,[team.id]:event.target.value}))}/><Button size="sm" disabled={!(member[team.id]??'').trim()} onClick={()=>void add(team)}>Add member</Button></>}</article>)}</div></PanelShell>
}
function Flags({api,tenant}:{api:WorkspaceContext['api'];tenant:string}){const qc=useQuery({queryKey:['system','flags',tenant],queryFn:()=>api.request<Flag[]>('/api/v1/feature-flags')});const mutation=useMutation({mutationFn:(row:Flag)=>api.json<Flag>(`/api/v1/feature-flags/${encodeURIComponent(row.key)}`,'PUT',{enabled:!row.enabled,description:row.description,rules:row.rules,revision:row.revision}),onSuccess:()=>void qc.refetch()});return <PanelShell title="Feature flags" subtitle="Revision-safe tenant flags">{qc.isError&&<ErrorNotice error={qc.error}/>}<div className="system-list">{qc.data?.map(row=><article key={row.key}><div><strong>{row.key}</strong><small>{row.description||'No description'}</small></div><StatusBadge status={row.enabled?'Enabled':'Disabled'}/><Button size="sm" onClick={()=>mutation.mutate(row)}>{row.enabled?'Disable':'Enable'}</Button></article>)}{qc.data?.length===0&&<EmptyState title="No feature flags" description="Create flags through the bounded API or app-specific administration workflow."/>}</div></PanelShell>}
function Jobs({api,tenant}:{api:WorkspaceContext['api'];tenant:string}){const query=useQuery({queryKey:['system','jobs',tenant],queryFn:()=>api.request<Job[]>('/api/v1/jobs'),refetchInterval:10000});return <PanelShell title="Durable jobs" subtitle="External work never holds the SQLite write lock">{query.isError&&<ErrorNotice error={query.error}/>}<div className="system-list">{query.data?.map(row=><article key={row.id}><div><strong>{row.job_type}</strong><small>{row.id} · {row.attempts}/{row.max_attempts} attempts</small></div><StatusBadge status={row.status}/><span>{row.error??<EmptyValue/>}</span></article>)}{query.data?.length===0&&<EmptyState title="Queue is empty" description="Feature code can enqueue registered durable jobs."/>}</div></PanelShell>}
function Notifications({api,rows,error,refresh}:{api:WorkspaceContext['api'];rows?:Notification[];error:unknown;refresh:()=>void}){const preferences=useQuery({queryKey:['system','notification-preferences'],queryFn:()=>api.request<NotificationPreference[]>('/api/v1/notification-preferences')});const mark=async(id:string)=>{await api.json(`/api/v1/notifications/${encodeURIComponent(id)}/read`,'POST');refresh()};const toggle=async(row:NotificationPreference)=>{await api.json(`/api/v1/notification-preferences/${encodeURIComponent(row.kind)}`,'PUT',{enabled:!row.enabled,revision:row.revision});await preferences.refetch()};return <PanelShell title="Notifications" subtitle="Private tenant/user inbox">{error!==null&&error!==undefined&&<ErrorNotice error={error}/>}<div className="system-list">{rows?.map(row=><article key={row.id} className={row.read_at?'':'unread'}><div><strong>{row.title}</strong><small>{row.kind} · {new Date(row.created_at).toLocaleString()}</small><p>{row.body}</p></div>{row.read_at?<Badge>Read</Badge>:<Button size="sm" onClick={()=>void mark(row.id)}>Mark read</Button>}</article>)}{rows?.length===0&&<EmptyState title="No notifications" description="This inbox contains only notifications addressed to the signed-in user."/>}</div><section aria-label="Notification preferences" className="system-list"><h3>Notification preferences</h3>{preferences.isError&&<ErrorNotice error={preferences.error}/>} {preferences.data?.map(row=><article key={row.kind}><strong>{row.kind}</strong><StatusBadge status={row.enabled?'Enabled':'Muted'}/><Button size="sm" onClick={()=>void toggle(row)}>{row.enabled?'Mute':'Enable'}</Button></article>)}{preferences.data?.length===0&&<p className="muted">Preferences appear after you change a notification category.</p>}</section></PanelShell>}
function Webhooks({api,tenant}:{api:WorkspaceContext['api'];tenant:string}){const query=useQuery({queryKey:['system','webhooks',tenant],queryFn:()=>api.request<Hook[]>('/api/v1/webhooks')});return <PanelShell title="Outbound webhooks" subtitle="HTTPS + deployment allowlist + external secret references">{query.isError&&<ErrorNotice error={query.error}/>}<div className="system-list">{query.data?.map(row=><WebhookRow key={row.id} api={api} row={row}/>)}{query.data?.length===0&&<EmptyState title="No webhook endpoints" description="Endpoints require a deployment-reviewed HTTPS host allowlist and secret reference."/>}</div></PanelShell>}
function WebhookRow({api,row}:{api:WorkspaceContext['api'];row:Hook}){const deliveries=useQuery({queryKey:['system','webhook-deliveries',row.id],queryFn:()=>api.request<Delivery[]>(`/api/v1/webhooks/${encodeURIComponent(row.id)}/deliveries`),refetchInterval:row.enabled?15000:false});return <article><div><strong>{row.name}</strong><small>{row.url}</small><p>{row.topics.join(', ')}</p><small>{deliveries.data?.length??0} recent deliveries</small></div><StatusBadge status={row.enabled?'Enabled':'Disabled'}/><code>{row.secret_ref}</code>{deliveries.data?.[0]&&<span>{deliveries.data[0].status} · attempt {deliveries.data[0].attempts}</span>}</article>}
function AuditLog({api,tenant}:{api:WorkspaceContext['api'];tenant:string}){const query=useQuery({queryKey:['system','audit',tenant],queryFn:()=>api.request<Audit[]>('/api/v1/audit?limit=100')});return <PanelShell title="Audit trail" subtitle="Append-only record history"><div className="system-list">{query.data?.map(row=><article key={row.id}><div><strong>{row.workspace} · {row.action}</strong><small>{row.actor} · revision {row.revision} · {new Date(row.created_at).toLocaleString()}</small></div><code>{row.request_id}</code></article>)}</div></PanelShell>}
