import { useMemo,useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import type { RelationshipDefinition,RelationshipRead } from '../../generated/schema'
import type { BaseRecord,ProjectionProps } from './types'
import { ProjectionWorkspaceFrame } from './ProjectionWorkspaceFrame'
import { recordValue } from './projectionUtils'
import { criticalPath,shiftIsoDate } from './planningModel'
import { ErrorNotice } from '../ui/Notice'
function text(row:BaseRecord,key:string){const value=recordValue(row,key);return value==null?'':String(value)}
function num(row:BaseRecord,key:string){const value=Number(recordValue(row,key));return Number.isFinite(value)?value:0}
function iso(row:BaseRecord,key:string){return text(row,key).slice(0,10)}
export function PlanningWorkspace<T extends BaseRecord>(props:ProjectionProps<T>){
 const[selected,setSelected]=useState<string|null>(null);const client=useQueryClient();const entity=props.adapter.entityKey??props.adapter.key
 const definitions=useQuery({queryKey:['relationship-definitions',props.user,props.tenant],queryFn:({signal})=>props.api.request<RelationshipDefinition[]>('/api/v1/relationships/definitions',{signal})})
 const graph=useQuery({queryKey:['planning-relations',props.user,props.tenant,entity],queryFn:({signal})=>props.api.request<RelationshipRead[]>(`/api/v1/relationships/graph?${new URLSearchParams({entity,limit:'1000'})}`,{signal})})
 const nudge=useMutation({mutationFn:({row,days}:{row:T;days:number})=>{const draft=props.adapter.draft(row);return props.adapter.update(row,{...draft,start_date:shiftIsoDate(String(draft.start_date??''),days),end_date:shiftIsoDate(String(draft.end_date??''),days),baseline_start:draft.baseline_start?shiftIsoDate(String(draft.baseline_start),days):'',baseline_end:draft.baseline_end?shiftIsoDate(String(draft.baseline_end),days):''})},onSuccess:()=>{void client.invalidateQueries({queryKey:['records',props.user,props.tenant,props.adapter.key]})}})
 return <ProjectionWorkspaceFrame {...props} projectionKey="planning" title="Program planning" description="Canonical WBS, dependency and schedule workbench shared with table, board, Gantt, calendar and timeline projections." extraMetrics={rows=>[{label:'Milestones',value:rows.filter(row=>text(row,'milestone')==='true').length},{label:'Blocked',value:rows.filter(row=>text(row,'status')==='blocked').length}]}>{(rows,{openRow,peekRow})=>{
  if(definitions.isError||graph.isError)return <ErrorNotice error={definitions.error??graph.error}/>
  const relDefs=new Map((definitions.data??[]).map(value=>[value.key,value]));const relations=graph.data??[]
  const deps=relations.filter(edge=>relDefs.get(edge.definition_key)?.kind==='dependency'&&edge.source.entity===entity&&edge.target.entity===entity&&!edge.archived)
  const hierarchy=relations.filter(edge=>relDefs.get(edge.definition_key)?.kind==='hierarchy'&&!edge.archived)
  const path=criticalPath(rows.map(row=>({id:row.id,duration:num(row,'duration_days')})),deps.map(edge=>({source:edge.source.id,target:edge.target.id})));const critical=new Set(path)
  const current=rows.find(row=>row.id===selected)??rows[0];const dates=rows.flatMap(row=>[iso(row,'start_date'),iso(row,'end_date')]).filter(Boolean).sort();const min=dates[0]??'2026-01-01';const max=dates.at(-1)??min;const minTime=Date.parse(`${min}T00:00:00Z`);const span=Math.max(86400000,Date.parse(`${max}T00:00:00Z`)-minTime+86400000)
  const depth=(id:string)=>{let d=0,c=id,guard=0;while(guard++<20){const parent=hierarchy.find(edge=>edge.target.id===c);if(!parent)break;d++;c=parent.source.id}return d}
  return <div className="planning-workbench"><section className="planning-table"><header><span>Work breakdown</span><span>{rows.length} tasks</span></header>{rows.map(row=><button key={row.id} className={`${current?.id===row.id?'selected':''} ${critical.has(row.id)?'critical':''}`} style={{paddingLeft:`${14+depth(row.id)*18}px`}} onClick={()=>setSelected(row.id)}><span>{text(row,'milestone')==='true'?'◆':'▰'}</span><strong>{text(row,'title')}</strong><small>{text(row,'owner')||'Unassigned'}</small></button>)}</section><section className="planning-gantt"><header><time>{min}</time><strong>Baseline / actual / progress</strong><time>{max}</time></header>{rows.map(row=>{const start=Date.parse(`${iso(row,'start_date')}T00:00:00Z`);const end=Date.parse(`${iso(row,'end_date')}T00:00:00Z`)+86400000;const left=Math.max(0,((start-minTime)/span)*100);const width=Math.max(.9,((end-start)/span)*100);const bs=iso(row,'baseline_start'),be=iso(row,'baseline_end');const bleft=bs?Math.max(0,((Date.parse(`${bs}T00:00:00Z`)-minTime)/span)*100):left;const bwidth=be?Math.max(.9,((Date.parse(`${be}T00:00:00Z`)+86400000-Date.parse(`${bs}T00:00:00Z`))/span)*100):width;return <div className={`planning-track ${critical.has(row.id)?'critical':''}`} key={row.id}><button className="planning-baseline" style={{left:`${bleft}%`,width:`${bwidth}%`}} aria-label={`Baseline ${text(row,'title')}`}/><button className={`planning-bar ${text(row,'milestone')==='true'?'milestone':''}`} style={{left:`${left}%`,width:`${width}%`}} onClick={()=>setSelected(row.id)} title={`${text(row,'title')} · ${num(row,'progress')}%`}><i style={{width:`${num(row,'progress')}%`}}/></button></div>})}</section>{current&&<aside className="planning-inspector"><span className="eyebrow">Selected task</span><h2>{text(current,'title')}</h2><dl><div><dt>Status</dt><dd>{text(current,'status')}</dd></div><div><dt>Dates</dt><dd>{iso(current,'start_date')} → {iso(current,'end_date')}</dd></div><div><dt>Progress</dt><dd>{num(current,'progress')}%</dd></div><div><dt>Duration</dt><dd>{num(current,'duration_days')} days</dd></div><div><dt>Dependencies</dt><dd>{deps.filter(edge=>edge.source.id===current.id).length}</dd></div><div><dt>Critical path</dt><dd>{critical.has(current.id)?'Yes':'No'}</dd></div></dl><div className="toolbar-actions"><button onClick={()=>peekRow(current)}>Quick look</button><button onClick={()=>openRow(current)}>Dossier</button></div>{props.permissions.includes('write')&&<div className="planning-nudge"><button disabled={nudge.isPending} onClick={()=>nudge.mutate({row:current,days:-1})}>← Shift 1 day</button><button disabled={nudge.isPending} onClick={()=>nudge.mutate({row:current,days:1})}>Shift 1 day →</button></div>}{nudge.isError&&<ErrorNotice error={nudge.error}/>}<section><h3>Critical chain</h3><ol>{path.map(id=><li key={id}>{text(rows.find(row=>row.id===id)??current,'title')}</li>)}</ol></section></aside>}</div>
 }}</ProjectionWorkspaceFrame>
}
