import { useEffect, useMemo, useState } from 'react'
import type { FieldDefinition, ViewColumn, WorkspaceDefinition } from '../../generated/schema'
import { AppShell } from '../../platform/ui/AppShell'
import { WorkspaceShell } from '../../platform/ui/WorkspaceShell'
import { Dialog } from '../../platform/ui/Dialog'
import { BottomSheetShell, PeekShell } from '../../platform/ui/OverlayShell'
import { DrawerShell, InspectorShell, PanelShell } from '../../platform/ui/PanelShell'
import { SplitPaneShell } from '../../platform/ui/SplitPaneShell'
import { FloatingPanelShell } from '../../platform/ui/FloatingPanelShell'
import { CommandPalette, type PaletteCommand } from '../../platform/commands/CommandPalette'
import { DataGrid } from '../../platform/grid/DataGrid'
import { FieldInput } from '../../platform/workspace/FieldInput'
import type { BaseRecord, Draft } from '../../platform/workspace/types'
import type { ColorModePreference } from '../../platform/ui/theme'
import { AvatarGroup, Badge, Banner, BodyText, Button, ButtonGroup, Caption, CodeBlock, DefinitionList, Heading, HealthIndicator, InlineAlert, MetricDelta, MetricValue, ProgressBar, ProgressRing, RangeSlider, SegmentedControl, SeverityIndicator, Slider, StatusBadge, Subheading, Switch, Tag, TrendIndicator, UserIdentity } from '../../platform/ui/primitives'

type Section='overview'|'foundations'|'shells'|'table'|'forms'|'layouts'|'engines'
type LabRecord=BaseRecord&{title:string;status:string;owner:string;priority:string;updated_at:string}
const fields:FieldDefinition[]=[
 {key:'title',label:'Title',kind:'text',required:true,nullable:false,max_length:160,choices:[],minimum:null,maximum:null,step:null,unit:null,read_only:false},
 {key:'status',label:'Status',kind:'select',required:true,nullable:false,max_length:null,choices:['planned','active','blocked','complete'],minimum:null,maximum:null,step:null,unit:null,read_only:false},
 {key:'owner',label:'Owner',kind:'text',required:false,nullable:false,max_length:120,choices:[],minimum:null,maximum:null,step:null,unit:null,read_only:false},
 {key:'priority',label:'Priority',kind:'select',required:true,nullable:false,max_length:null,choices:['low','normal','high','critical'],minimum:null,maximum:null,step:null,unit:null,read_only:false},
 {key:'updated_at',label:'Updated',kind:'datetime',required:true,nullable:false,max_length:null,choices:[],minimum:null,maximum:null,step:null,unit:null,read_only:true},
]
const definition:WorkspaceDefinition={key:'lab_records',label:'Golden operational records',description:'Actual DataGrid, grouping, selection and column-state primitives.',schema_version:1,fields,columns:['title','status','owner','priority','updated_at'],capabilities:['search','filters','sorting','selection','bulk','saved_views','details','history','relationships'],primary_field:'title',filter_keys:['status','priority'],sort_keys:['title','status','priority','updated_at'],visualizations:['table','board','timeline','dashboard']}
const rows:LabRecord[]=[
 {id:'1',revision:3,archived:false,title:'Qualify mounted storage',status:'active',owner:'Platform',priority:'critical',updated_at:'2026-09-07T19:20:00Z'},
 {id:'2',revision:7,archived:false,title:'Rack cable trace review',status:'blocked',owner:'Infrastructure',priority:'high',updated_at:'2026-09-07T18:40:00Z'},
 {id:'3',revision:2,archived:false,title:'SPC process-window baseline',status:'active',owner:'Process Eng',priority:'high',updated_at:'2026-09-07T17:10:00Z'},
 {id:'4',revision:11,archived:false,title:'Knowledge verification workflow',status:'complete',owner:'Operations',priority:'normal',updated_at:'2026-09-07T16:35:00Z'},
 {id:'5',revision:1,archived:false,title:'Incident error-budget drill',status:'planned',owner:'SRE',priority:'normal',updated_at:'2026-09-07T15:05:00Z'},
]
const formFields:FieldDefinition[]=[
 fields[0]!,fields[1]!,
 {key:'power',label:'Power budget',kind:'unit_number',required:true,nullable:false,max_length:null,choices:[],minimum:0,maximum:30,step:.1,unit:'kW',read_only:false},
 {key:'tags',label:'Capabilities',kind:'multiselect',required:false,nullable:false,max_length:null,choices:['rack','graph','spc','knowledge','incident'],minimum:null,maximum:null,step:null,unit:null,read_only:false},
 {key:'metadata',label:'Structured metadata',kind:'json',required:false,nullable:false,max_length:50000,choices:[],minimum:null,maximum:null,step:null,unit:null,read_only:false},
 {key:'notes',label:'Engineering notes',kind:'markdown',required:false,nullable:false,max_length:20000,choices:[],minimum:null,maximum:null,step:null,unit:null,read_only:false},
]
const sections:Array<{id:Section;label:string;hint:string}>=[
 {id:'overview',label:'Overview',hint:'Design law and capability map'},
 {id:'foundations',label:'Foundations',hint:'Typography, controls and indicators'},
 {id:'shells',label:'Shells & windows',hint:'Actual managed surfaces'},
 {id:'table',label:'Operational table',hint:'Grid + grouping + selection'},
 {id:'forms',label:'Schema forms',hint:'Typed reusable controls'},
 {id:'layouts',label:'Adaptive layout',hint:'Split/docked workspace grammar'},
 {id:'engines',label:'Engine catalog',hint:'Production workspace families'},
]

export function ExperienceLab(){
 const [section,setSection]=useState<Section>('overview')
 const [mode,setMode]=useState<ColorModePreference>('dark')
 const [personality,setPersonality]=useState<'operations'|'clarity'|'minimal'>('operations')
 const [density,setDensity]=useState<'comfortable'|'compact'|'engineering'>('compact')
 const [commandOpen,setCommandOpen]=useState(false)
 useEffect(()=>{const root=document.documentElement;root.dataset.theme=personality;root.dataset.density=density;if(mode==='system')delete root.dataset.mode;else root.dataset.mode=mode},[mode,personality,density])
 const commands=useMemo<PaletteCommand[]>(()=>sections.map(item=>({id:`lab.${item.id}`,label:`Open ${item.label}`,description:item.hint,keywords:['lab',item.id],action:()=>setSection(item.id)})),[])
 return <AppShell sidebar={<><div className="brand"><span className="brand-mark">R</span><div><strong>React-FastAPI Base</strong><span>Experience Lab</span></div></div><div className="sidebar-section">PLATFORM LAB</div><nav aria-label="Lab navigation">{sections.map(item=><button key={item.id} className={section===item.id?'active':''} onClick={()=>setSection(item.id)}><span aria-hidden="true">▦</span><span><strong>{item.label}</strong><small>{item.hint}</small></span></button>)}</nav><div className="sidebar-bottom"><span className="status-dot"/><span>Actual platform components</span><small>No production records</small></div></>} header={<><div className="breadcrumb">Experience Lab / <strong>{sections.find(item=>item.id===section)?.label}</strong></div><div className="shell-controls"><button className="command-trigger" onClick={()=>setCommandOpen(true)}>⌘K</button><label className="lab-control">Appearance<select value={mode} onChange={event=>setMode(event.target.value as ColorModePreference)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="lab-control">Personality<select value={personality} onChange={event=>setPersonality(event.target.value as typeof personality)}><option value="operations">Operations</option><option value="clarity">Clarity</option><option value="minimal">Minimal</option></select></label><label className="lab-control">Density<select value={density} onChange={event=>setDensity(event.target.value as typeof density)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="engineering">Engineering</option></select></label></div></>} release="Living platform showroom · actual reusable shells and controls · synthetic/disposable fixtures only">
  <CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} commands={commands}/>
  {section==='overview'&&<Overview/>}{section==='foundations'&&<FoundationsGallery/>}{section==='shells'&&<ShellGallery/>}{section==='table'&&<TableGallery/>}{section==='forms'&&<FormsGallery/>}{section==='layouts'&&<LayoutGallery/>}{section==='engines'&&<EngineGallery/>}
 </AppShell>
}

function Overview(){return <WorkspaceShell eyebrow="Production platform" title="High-density application construction system" description="Canonical entities + typed relationships + reusable visualization engines + platform-owned interaction grammar." metrics={[{label:'Workspace families',value:'20+'},{label:'Surface kinds',value:'10'},{label:'Canonical principle',value:'One source',className:'summary-word'},{label:'Theme modes',value:'3 × 3',className:'summary-word'}]}>
 <div className="lab-overview-grid"><PanelShell title="Data model first" subtitle="Define canonical entities once"><ul><li>Typed fields & validation</li><li>Revision/audit/lifecycle</li><li>Generated API + client contracts</li><li>Source-of-truth relationships</li></ul></PanelShell><PanelShell title="Visualization projection" subtitle="Choose without copying data"><div className="capability-chips">{['Table','Board','Timeline','Calendar','Gantt','Dashboard','Graph','Rack','Knowledge','Investigation','SPC','Wafer'].map(value=><span key={value}>{value}</span>)}</div></PanelShell><PanelShell title="Interaction law" subtitle="Complexity organized, not removed"><ul><li>Command palette + Peek</li><li>Context actions + bulk preview</li><li>Dossier/history/relationships</li><li>Adaptive shell and focus patterns</li></ul></PanelShell></div>
 </WorkspaceShell>}

function FoundationsGallery(){
 const[toggle,setToggle]=useState('Operations'),[enabled,setEnabled]=useState(true),[slider,setSlider]=useState(68),[range,setRange]=useState<[number,number]>([22,78])
 return <WorkspaceShell eyebrow="Design system" title="Foundation primitives" description="Actual reusable typography, controls, indicators and feedback components rendered from semantic tokens.">
  <div className="lab-foundation-grid">
   <PanelShell title="Typography & content" subtitle="Hierarchy stays stable across themes and density"><div className="lab-stack"><Heading level={2}>Engineering workspace heading</Heading><Subheading>Dense contextual subtitle without visual noise</Subheading><BodyText>Canonical data and related evidence remain readable while high-value context stays on screen.</BodyText><Caption>Operational context</Caption><div className="lab-metrics"><MetricValue value="99.94%" label="Availability"/><MetricDelta value={2.7}/><TrendIndicator value={-1.4}/></div><DefinitionList items={[{label:'Owner',value:'Platform Engineering'},{label:'Revision',value:'r17'},{label:'Scope',value:'Company'}]}/><CodeBlock language="typescript">{`defineEntity({ key: 'equipment', authority: 'canonical' })`}</CodeBlock></div></PanelShell>
   <PanelShell title="Controls" subtitle="Same action grammar everywhere"><div className="lab-stack"><ButtonGroup><Button tone="accent">Primary</Button><Button>Secondary</Button><Button tone="danger">Destructive</Button></ButtonGroup><SegmentedControl label="Workspace mode" value={toggle} onChange={setToggle} options={[{value:'Operations',label:'Operations'},{value:'Trace',label:'Trace'},{value:'Analyze',label:'Analyze'}]}/><Switch checked={enabled} onCheckedChange={setEnabled} label="Context-aware actions"/><Slider label="Density signal" min={0} max={100} value={slider} onChange={event=>setSlider(Number(event.target.value))}/><RangeSlider label="Process window" minimum={0} maximum={100} value={range} onChange={setRange}/><div className="capability-chips"><Tag>Saved view</Tag><Tag>Keyboard</Tag><Tag>Revision-safe</Tag></div></div></PanelShell>
   <PanelShell title="Indicators & feedback" subtitle="Semantic state, never arbitrary color"><div className="lab-stack"><div className="lab-indicator-row"><StatusBadge status="Healthy"/><StatusBadge status="Degraded"/><SeverityIndicator severity="critical"/><HealthIndicator health="healthy"/></div><ProgressBar label="Release evidence" value={74}/><div className="lab-indicator-row"><ProgressRing value={86} label="SLO"/><AvatarGroup people={[{name:'Platform Engineering'},{name:'Process Engineering'},{name:'SRE'},{name:'Operations'},{name:'Security'}]}/><UserIdentity name="Alex Operator" detail="Editor · Tenant A"/></div><Banner tone="warning" title="Qualification required">Company storage remains fail-closed until operator evidence is attached.</Banner><InlineAlert tone="success">Revision, audit and relationship contracts are active.</InlineAlert><Badge tone="accent">Canonical source</Badge></div></PanelShell>
  </div>
 </WorkspaceShell>
}

function ShellGallery(){
 const [modal,setModal]=useState(false),[drawer,setDrawer]=useState(false),[sheet,setSheet]=useState(false),[peek,setPeek]=useState(false),[popover,setPopover]=useState<{x:number;y:number}|null>(null)
 return <WorkspaceShell eyebrow="Surface Manager" title="Shell & window gallery" description="Headers, body scrolling, footers, close/expand, focus, Escape and layering come from platform shells—not feature code." commandBar={<div className="toolbar-actions"><button onClick={()=>setModal(true)}>Form modal</button><button onClick={()=>setDrawer(true)}>Drawer</button><button onClick={()=>setSheet(true)}>Bottom sheet</button><button onClick={()=>setPeek(true)}>Peek</button><button onClick={event=>{const rect=event.currentTarget.getBoundingClientRect();setPopover({x:rect.left,y:rect.bottom+8})}}>Popover</button></div>}>
  <div className="lab-shell-grid"><PanelShell title="Panel shell" subtitle="Reusable embedded chrome" controls={<button className="icon-button">⋯</button>} footer={<><span className="muted">Persistent surface</span><button>Action</button></>}><p>Main content is feature-owned. Chrome, spacing and footer grammar are platform-owned.</p></PanelShell><InspectorShell title="Inspector shell" subtitle="Selection-driven context"><dl className="lab-kv"><div><dt>Status</dt><dd>Active</dd></div><div><dt>Revision</dt><dd>17</dd></div><div><dt>Relationships</dt><dd>8</dd></div></dl></InspectorShell></div>
  {modal&&<Dialog title="Standard form shell" subtitle="Sticky chrome + dirty close + expand/restore" wide onClose={()=>setModal(false)} footer={<><span className="muted">Validation remains visible.</span><button onClick={()=>setModal(false)}>Cancel</button><button className="primary">Save</button></>}><div className="form-grid"><label>Name<input defaultValue="Equipment A-102"/></label><label>Status<select defaultValue="active"><option>active</option><option>maintenance</option></select></label><label className="full-width">Description<textarea rows={5} defaultValue="Domain content sits inside the same shell contract."/></label></div></Dialog>}
  <DrawerShell open={drawer} onClose={()=>setDrawer(false)} title="Right drawer" subtitle="Secondary but persistent context"><p>Drawers become mobile-safe overlays while retaining the same shell anatomy.</p></DrawerShell>
  <BottomSheetShell open={sheet} onClose={()=>setSheet(false)} title="Bottom sheet" subtitle="Mobile secondary context"><p>Same content contract; presentation changes with intent and viewport.</p></BottomSheetShell>
  <PeekShell open={peek} onClose={()=>setPeek(false)} title="Quick Look" subtitle="Inspect without losing workspace context"><dl className="lab-kv"><div><dt>Entity</dt><dd>Equipment</dd></div><div><dt>Rack</dt><dd>R12 · U18</dd></div><div><dt>Connections</dt><dd>4</dd></div></dl></PeekShell>
  {popover&&<FloatingPanelShell open title="Context actions" anchor={popover} onClose={()=>setPopover(null)} width={260}><div className="context-action-list"><button>Quick Look</button><button>Open dossier</button><button>Edit</button><button className="danger-text">Archive</button></div></FloatingPanelShell>}
 </WorkspaceShell>
}

function TableGallery(){const[columns,setColumns]=useState<ViewColumn[]>([]),[selection,setSelection]=useState<LabRecord[]>([]),[groupBy,setGroupBy]=useState('status'),[message,setMessage]=useState('');return <WorkspaceShell eyebrow="Operational table" title="Golden interaction baseline" description="Actual reusable DataGrid + license-free grouped mode + selection/context/Peek hooks." metrics={[{label:'Rows',value:rows.length},{label:'Selected',value:selection.length},{label:'Grouping',value:groupBy||'None',className:'summary-word'}]} commandBar={<><label>Group by<select value={groupBy} onChange={event=>setGroupBy(event.target.value)}><option value="">None</option><option value="status">Status</option><option value="priority">Priority</option></select></label><button onClick={()=>setColumns([])}>Reset columns</button></>} notice={message?<div className="notice" role="status">{message}</div>:undefined}>
 <DataGrid rows={rows} definition={definition} density="compact" columns={columns} scope={`lab:${groupBy}`} groupBy={groupBy} onOpen={row=>setMessage(`Open dossier: ${row.title}`)} onPeek={row=>setMessage(`Quick Look: ${row.title}`)} onContext={(row)=>setMessage(`Context menu requested for ${row.title}`)} onSelection={setSelection} onColumns={setColumns}/>
 </WorkspaceShell>}

function FormsGallery(){const[draft,setDraft]=useState<Draft>({title:'Process excursion review',status:'active',power:'8.5',tags:'["spc","knowledge"]',metadata:'{\n  "owner": "process-eng",\n  "line": "F12"\n}',notes:'## Review\n\nCapture evidence, validation and rollback.'});return <WorkspaceShell eyebrow="Schema-driven forms" title="Typed engineering controls" description="The same FieldDefinition contract drives generated forms and validates server persistence."><PanelShell title="Form controls" subtitle="Text, enum, units, multiselect, JSON and Markdown"><div className="form-grid">{formFields.map((field,index)=><label key={field.key} className={['json','markdown','code','multiselect'].includes(field.kind)?'full-width':''}><span>{field.label}{field.unit&&<> · {field.unit}</>}</span><FieldInput field={field} draft={draft} onChange={setDraft} invalid={false} autoFocus={index===0}/></label>)}</div></PanelShell></WorkspaceShell>}

function LayoutGallery(){return <WorkspaceShell eyebrow="Adaptive workbench" title="Split, inspector and focus-ready layout grammar" description="Complex engineering work stays visible on large displays and collapses into drawers/sheets on constrained screens."><SplitPaneShell initial={64} primary={<PanelShell title="Primary canvas" subtitle="Graph / Rack / Gantt / Wafer"><div className="lab-canvas"><span>Navigator</span><strong>Primary engineering surface</strong><small>Selection drives contextual inspection</small></div></PanelShell>} secondary={<InspectorShell title="Context inspector" subtitle="Selection properties"><dl className="lab-kv"><div><dt>Object</dt><dd>Node A-17</dd></div><div><dt>Health</dt><dd>Nominal</dd></div><div><dt>Dependencies</dt><dd>12</dd></div><div><dt>History</dt><dd>8 revisions</dd></div></dl></InspectorShell>}/></WorkspaceShell>}

function EngineGallery(){const engines=[['Operational Table','Search · filters · saved views · grouping · context · bulk'],['Rack Estate','Placement · power · ports · cables · tracing'],['Diagram Designer','Nodes · edges · inspector · validation · auto-layout'],['Planning','WBS · dependencies · baseline · progress · critical path'],['Knowledge','Documents · procedures · verification · backlinks'],['Investigation / Risk','Evidence · causes · mitigation · server-owned scoring'],['SPC / Analytics','I-MR · capability · EWMA · Pareto · rule signals'],['Semiconductor','Wafer · lot · equipment state · recipe compare'],['Software Engineering','Pipeline · trace · incident · SLO/error budget']];return <WorkspaceShell eyebrow="Reusable engine catalog" title="Domain packs compose platform engines" description="These are implemented workspace families in the source tree; the Lab indexes their public capability contract."><div className="engine-catalog">{engines.map(([title,detail])=><article key={title}><span className="eyebrow">Stable direction</span><h2>{title}</h2><p>{detail}</p><div className="capability-chips"><span>Canonical data</span><span>Relationships</span><span>Dossier</span><span>History</span></div></article>)}</div></WorkspaceShell>}
