import { useEffect, useMemo, useState, type AnchorHTMLAttributes, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode } from 'react'

type Tone='neutral'|'info'|'success'|'warning'|'danger'|'accent'
type Size='sm'|'md'|'lg'
const classes=(...values:Array<string|false|undefined>)=>values.filter(Boolean).join(' ')

export function Heading({children,level=1,className=''}:{children:ReactNode;level?:1|2|3|4;className?:string}){const Tag=`h${level}` as const;return <Tag className={classes('ui-heading',`level-${level}`,className)}>{children}</Tag>}
export function Subheading({children,className=''}:{children:ReactNode;className?:string}){return <p className={classes('ui-subheading',className)}>{children}</p>}
export function BodyText({children,className=''}:{children:ReactNode;className?:string}){return <p className={classes('ui-body-text',className)}>{children}</p>}
export function SecondaryText({children,className=''}:{children:ReactNode;className?:string}){return <span className={classes('ui-secondary-text',className)}>{children}</span>}
export function Caption({children,className=''}:{children:ReactNode;className?:string}){return <span className={classes('ui-caption',className)}>{children}</span>}
export function LabelText({children,className=''}:{children:ReactNode;className?:string}){return <span className={classes('ui-label',className)}>{children}</span>}
export function MonoText({children,className=''}:{children:ReactNode;className?:string}){return <span className={classes('ui-mono',className)}>{children}</span>}
export function InlineCode({children}:{children:ReactNode}){return <code className="ui-inline-code">{children}</code>}
export function CodeBlock({children,language}:{children:string;language?:string}){return <div className="ui-code-block"><header><span>{language??'text'}</span><CopyButton value={children}/></header><pre><code>{children}</code></pre></div>}
export function Link({children,...props}:AnchorHTMLAttributes<HTMLAnchorElement>){return <a {...props} className={classes('ui-link',props.className)}>{children}</a>}
export function ExternalLink({children,...props}:AnchorHTMLAttributes<HTMLAnchorElement>){return <a {...props} target="_blank" rel="noreferrer noopener" className={classes('ui-link','external',props.className)}>{children}<span aria-hidden="true">↗</span></a>}
export function TruncatedText({children,title}:{children:string;title?:string}){return <span className="ui-truncate" title={title??children}>{children}</span>}
export function ExpandableText({children,limit=180}:{children:string;limit?:number}){const[open,setOpen]=useState(false);const clipped=children.length>limit;return <span className="ui-expandable-text"><span>{!clipped||open?children:`${children.slice(0,limit).trimEnd()}…`}</span>{clipped&&<button type="button" className="ui-link-button" onClick={()=>setOpen(v=>!v)}>{open?'Show less':'Show more'}</button>}</span>}
export function CopyableText({children}:{children:string}){return <span className="ui-copyable"><MonoText>{children}</MonoText><CopyButton value={children}/></span>}
export function KeyValue({label,value}:{label:ReactNode;value:ReactNode}){return <div className="ui-key-value"><dt>{label}</dt><dd>{value}</dd></div>}
export function DefinitionList({items}:{items:Array<{label:ReactNode;value:ReactNode}>}){return <dl className="ui-definition-list">{items.map((item,index)=><KeyValue key={index} label={item.label} value={item.value}/>)}</dl>}
export function MetricValue({value,label}:{value:ReactNode;label?:ReactNode}){return <span className="ui-metric-value"><strong>{value}</strong>{label&&<small>{label}</small>}</span>}
export function MetricDelta({value,suffix='%'}:{value:number;suffix?:string}){const tone=value>0?'positive':value<0?'negative':'flat';return <span className={classes('ui-metric-delta',tone)}>{value>0?'+':''}{value}{suffix}</span>}
export function Timestamp({value}:{value:string|Date}){const date=value instanceof Date?value:new Date(value);return <time className="ui-timestamp" dateTime={date.toISOString()}>{new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(date)}</time>}
export function RelativeTime({value,now=new Date()}:{value:string|Date;now?:Date}){const date=value instanceof Date?value:new Date(value);const seconds=Math.round((date.getTime()-now.getTime())/1000);const abs=Math.abs(seconds);const [amount,unit]:[number,Intl.RelativeTimeFormatUnit]=abs<60?[seconds,'second']:abs<3600?[Math.round(seconds/60),'minute']:abs<86400?[Math.round(seconds/3600),'hour']:[Math.round(seconds/86400),'day'];return <time className="ui-relative-time" dateTime={date.toISOString()} title={date.toLocaleString()}>{new Intl.RelativeTimeFormat(undefined,{numeric:'auto'}).format(amount,unit)}</time>}
export function DurationText({seconds}:{seconds:number}){const safe=Math.max(0,seconds);const h=Math.floor(safe/3600),m=Math.floor((safe%3600)/60),s=Math.floor(safe%60);return <MonoText>{h?`${h}h `:''}{m?`${m}m `:''}{s}s</MonoText>}
export function UserIdentity({name,detail,initials}:{name:string;detail?:string;initials?:string}){return <span className="ui-user-identity"><Avatar name={name} initials={initials}/><span><strong>{name}</strong>{detail&&<small>{detail}</small>}</span></span>}
export function EmptyValue({label='—'}:{label?:string}){return <span className="ui-empty-value" aria-label="No value">{label}</span>}

export function Button({tone='neutral',size='md',busy=false,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{tone?:Tone;size?:Size;busy?:boolean}){return <button {...props} disabled={busy||props.disabled} className={classes('ui-button',`tone-${tone}`,`size-${size}`,props.className)}>{busy&&<Spinner size="sm"/>}{children}</button>}
export function IconButton({label,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string;busy?:boolean}){return <Button {...props} className={classes('ui-icon-button',props.className)} aria-label={label} title={props.title??label}>{children}</Button>}
export function ButtonGroup({children,label='Actions'}:{children:ReactNode;label?:string}){return <div className="ui-button-group" role="group" aria-label={label}>{children}</div>}
export function SplitButton({label,onPrimary,children,disabled=false}:{label:string;onPrimary:()=>void;children:ReactNode;disabled?:boolean}){const[open,setOpen]=useState(false);return <div className="ui-split-button"><Button disabled={disabled} onClick={onPrimary}>{label}</Button><IconButton disabled={disabled} label={`${label} options`} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>⌄</IconButton>{open&&<div className="ui-split-menu">{children}</div>}</div>}
export function ToggleButton({pressed,onPressedChange,children,...props}:Omit<ButtonHTMLAttributes<HTMLButtonElement>,'onChange'>&{pressed:boolean;onPressedChange:(value:boolean)=>void}){return <Button {...props} aria-pressed={pressed} className={classes('ui-toggle-button',pressed&&'selected',props.className)} onClick={event=>{props.onClick?.(event);if(!event.defaultPrevented)onPressedChange(!pressed)}}>{children}</Button>}
export function ToggleGroup({value,onChange,options,label}:{value:string;onChange:(value:string)=>void;options:Array<{value:string;label:string}>;label:string}){return <div className="ui-toggle-group" role="group" aria-label={label}>{options.map(option=><ToggleButton key={option.value} pressed={value===option.value} onPressedChange={()=>onChange(option.value)}>{option.label}</ToggleButton>)}</div>}
export const SegmentedControl=ToggleGroup
export function Checkbox({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:ReactNode}){return <label className="ui-check"><input {...props} type="checkbox"/><span>{label}</span></label>}
export function Radio({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:ReactNode}){return <label className="ui-check"><input {...props} type="radio"/><span>{label}</span></label>}
export function Switch({checked,onCheckedChange,label,disabled=false}:{checked:boolean;onCheckedChange:(value:boolean)=>void;label:ReactNode;disabled?:boolean}){return <label className={classes('ui-switch',disabled&&'disabled')}><button type="button" role="switch" aria-checked={checked} disabled={disabled} onClick={()=>onCheckedChange(!checked)}><span/></button><span>{label}</span></label>}
export function Slider({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:ReactNode}){return <label className="ui-slider"><span>{label}</span><input {...props} type="range"/><output>{props.value}</output></label>}
export function RangeSlider({minimum,maximum,value,onChange,label}:{minimum:number;maximum:number;value:[number,number];onChange:(value:[number,number])=>void;label:string}){return <fieldset className="ui-range-slider"><legend>{label}</legend><input type="range" min={minimum} max={maximum} value={value[0]} onChange={e=>onChange([Math.min(Number(e.target.value),value[1]),value[1]])}/><input type="range" min={minimum} max={maximum} value={value[1]} onChange={e=>onChange([value[0],Math.max(Number(e.target.value),value[0])])}/><output>{value[0]}–{value[1]}</output></fieldset>}
export function LinkButton({children,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className={classes('ui-link-button',props.className)}>{children}</button>}
export function CopyButton({value,label='Copy'}:{value:string;label?:string}){const[copied,setCopied]=useState(false);const copy=async()=>{try{await navigator.clipboard.writeText(value);setCopied(true)}catch{setCopied(false)}};useEffect(()=>{if(!copied)return;const timer=window.setTimeout(()=>setCopied(false),1200);return()=>window.clearTimeout(timer)},[copied]);return <IconButton type="button" label={copied?'Copied':label} onClick={()=>void copy()}>{copied?'✓':'⧉'}</IconButton>}
export function FavoriteButton({active,onChange}:{active:boolean;onChange:(value:boolean)=>void}){return <ToggleButton pressed={active} onPressedChange={onChange} aria-label={active?'Remove favorite':'Add favorite'}>{active?'★':'☆'}</ToggleButton>}
export function PinButton({active,onChange}:{active:boolean;onChange:(value:boolean)=>void}){return <ToggleButton pressed={active} onPressedChange={onChange} aria-label={active?'Unpin':'Pin'}>{active?'●':'○'}</ToggleButton>}
export function RefreshButton({onRefresh,busy=false}:{onRefresh:()=>void;busy?:boolean}){return <IconButton label="Refresh" busy={busy} onClick={onRefresh}>↻</IconButton>}

export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:Tone}){return <span className={classes('ui-badge',`tone-${tone}`)}>{children}</span>}
export function StatusBadge({status}:{status:string}){const normalized=status.toLowerCase();const tone:Tone=/error|failed|critical|blocked|down/.test(normalized)?'danger':/warning|pending|degraded|review/.test(normalized)?'warning':/active|ready|healthy|complete|success|up/.test(normalized)?'success':'neutral';return <Badge tone={tone}>{status}</Badge>}
export function StatusDot({tone='neutral',label}:{tone?:Tone;label:string}){return <span className={classes('ui-status-dot',`tone-${tone}`)}><i aria-hidden="true"/><span>{label}</span></span>}
export function Chip({children,removable=false,onRemove}:{children:ReactNode;removable?:boolean;onRemove?:()=>void}){return <span className="ui-chip"><span>{children}</span>{removable&&<button type="button" aria-label="Remove" onClick={onRemove}>×</button>}</span>}
export const Tag=Chip
export function CountBadge({count}:{count:number}){return <Badge tone="neutral">{count>999?'999+':count}</Badge>}
export function Avatar({name,initials,size='md'}:{name:string;initials?:string;size?:Size}){const text=initials??name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join('');return <span className={classes('ui-avatar',`size-${size}`)} aria-label={name}>{text||'?'}</span>}
export function AvatarGroup({people,max=4}:{people:Array<{name:string;initials?:string}>;max?:number}){const visible=people.slice(0,max),remaining=people.length-visible.length;return <span className="ui-avatar-group" aria-label={people.map(p=>p.name).join(', ')}>{visible.map(person=><Avatar key={person.name} {...person} size="sm"/>)}{remaining>0&&<Avatar name={`${remaining} more`} initials={`+${remaining}`} size="sm"/>}</span>}
export function PresenceIndicator({online,label}:{online:boolean;label?:string}){return <StatusDot tone={online?'success':'neutral'} label={label??(online?'Online':'Offline')}/>}
export function ProgressBar({value,max=100,label}:{value:number;max?:number;label?:string}){const pct=Math.max(0,Math.min(100,max>0?value/max*100:0));return <div className="ui-progress"><div className="ui-progress-label"><span>{label}</span><span>{Math.round(pct)}%</span></div><div role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={max}><i style={{width:`${pct}%`}}/></div></div>}
export function ProgressRing({value,max=100,label}:{value:number;max?:number;label?:string}){const pct=Math.max(0,Math.min(100,max>0?value/max*100:0));return <span className="ui-progress-ring" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={max} style={{'--progress':`${pct}%`} as HTMLAttributes<HTMLElement>['style']}><span>{Math.round(pct)}%</span>{label&&<small>{label}</small>}</span>}
export function Spinner({size='md',label='Loading'}:{size?:Size;label?:string}){return <span className={classes('ui-spinner',`size-${size}`)} role="status" aria-label={label}/>} 
export function Skeleton({width='100%',height=12}:{width?:string|number;height?:string|number}){return <span className="ui-skeleton" aria-hidden="true" style={{width,height}}/>}
export function HealthIndicator({health}:{health:'healthy'|'degraded'|'down'|'unknown'}){const tone:Tone=health==='healthy'?'success':health==='degraded'?'warning':health==='down'?'danger':'neutral';return <StatusDot tone={tone} label={health}/>} 
export function TrendIndicator({value}:{value:number}){return <span className={classes('ui-trend',value>0?'positive':value<0?'negative':'flat')}><span aria-hidden="true">{value>0?'↗':value<0?'↘':'→'}</span>{Math.abs(value).toFixed(1)}%</span>}
export function SeverityIndicator({severity}:{severity:'info'|'low'|'medium'|'high'|'critical'}){const tone:Tone=severity==='critical'||severity==='high'?'danger':severity==='medium'?'warning':severity==='info'?'info':'neutral';return <Badge tone={tone}>{severity}</Badge>}
export function SLAIndicator({remainingPercent}:{remainingPercent:number}){const tone:Tone=remainingPercent<=0?'danger':remainingPercent<25?'warning':'success';return <span className="ui-sla"><ProgressBar value={remainingPercent}/><Badge tone={tone}>{remainingPercent.toFixed(1)}% budget</Badge></span>}

export function Banner({tone='info',title,children,actions}:{tone?:Tone;title:ReactNode;children?:ReactNode;actions?:ReactNode}){return <section className={classes('ui-banner',`tone-${tone}`)} role={tone==='danger'?'alert':'status'}><div><strong>{title}</strong>{children&&<div>{children}</div>}</div>{actions&&<div className="ui-banner-actions">{actions}</div>}</section>}
export function InlineAlert({tone='info',children}:{tone?:Tone;children:ReactNode}){return <div className={classes('ui-inline-alert',`tone-${tone}`)} role={tone==='danger'?'alert':'status'}>{children}</div>}

export function useDisclosure(initial=false){const[open,setOpen]=useState(initial);return useMemo(()=>({open,show:()=>setOpen(true),hide:()=>setOpen(false),toggle:()=>setOpen(value=>!value),setOpen}),[open])}
