// Generated by scripts/generate_catalog_registry.py; do not edit by hand.
import type { CatalogVariant } from './variants'

export const catalogVariants = [
  {
    "id": "Heading",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Subheading",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "BodyText",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "SecondaryText",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Caption",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Label",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "MonoText",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "InlineCode",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "CodeBlock",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Link",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "ExternalLink",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "TruncatedText",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "ExpandableText",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "CopyableText",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "KeyValue",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "DefinitionList",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "MetricValue",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "MetricDelta",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Timestamp",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "RelativeTime",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Duration",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "UserIdentity",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "EmptyValue",
    "category": "Typography and content",
    "family": "content",
    "required": true
  },
  {
    "id": "Button",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "IconButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "SplitButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "ButtonGroup",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "ToggleButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "ToggleGroup",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "SegmentedControl",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "Checkbox",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "Radio",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "Switch",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "Slider",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "RangeSlider",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "LinkButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "CopyButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "FavoriteButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "PinButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "RefreshButton",
    "category": "Controls",
    "family": "control",
    "required": true
  },
  {
    "id": "Badge",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "StatusBadge",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "StatusDot",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "Chip",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "Tag",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "CountBadge",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "Avatar",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "AvatarGroup",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "PresenceIndicator",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "ProgressBar",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "ProgressRing",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "Spinner",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "Skeleton",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "HealthIndicator",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "TrendIndicator",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "SeverityIndicator",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "SLAIndicator",
    "category": "Indicators",
    "family": "indicator",
    "required": true
  },
  {
    "id": "Modal",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "AlertDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ConfirmDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DestructiveConfirmDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "FormDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "WizardDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DossierDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ComparisonDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "FullScreenDialog",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DrawerLeft",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DrawerRight",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DrawerBottom",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "InspectorDrawer",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DetailsDrawer",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Popover",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Dropdown",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ComboDropdown",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "HoverCard",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Tooltip",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ContextMenu",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Menu",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Submenu",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ActionMenu",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "AnchoredFlyout",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "FloatingPanel",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "CommandPalette",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "SearchPalette",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "QuickSwitcher",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Toast",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ToastStack",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "NotificationCenter",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "NotificationDrawer",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "Banner",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "InlineAlert",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "BottomSheet",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "SideSheet",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "MasterDetailPane",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "SplitPane",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "ResizablePane",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "SidecarPanel",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DockedPanel",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "CollapsiblePanel",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "FloatingInspector",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "DockWorkspace",
    "category": "Windows and overlays",
    "family": "surface",
    "required": true
  },
  {
    "id": "TextInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "Textarea",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "PasswordInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "SearchInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "IntegerInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DecimalInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ScientificNumberInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "CurrencyInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "PercentInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "UnitAwareNumberInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "EmailInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "PhoneInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "URLInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "Select",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "MultiSelect",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "Combobox",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "Autocomplete",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "TagInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "TokenInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "SearchableSelector",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "CheckboxGroup",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "RadioGroup",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DatePicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "TimePicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DateTimePicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DateRangePicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "MonthPicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "YearPicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DurationInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "TimezonePicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "FileInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "MultiFileUpload",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DragDropUpload",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ImageUpload",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ColorPicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "IconPicker",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "KeyValueEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ArrayEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ObjectEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "JSONEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "YAMLEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "CodeEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "MarkdownEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "RichTextEditor",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "CronBuilder",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ExpressionBuilder",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "FilterBuilder",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "QueryBuilder",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "RuleBuilder",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "FormulaBuilder",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "CoordinateInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "RangeInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "ToleranceInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "EngineeringUnitInput",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "DynamicSchemaForm",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "TabbedForm",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "SectionedForm",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "WizardForm",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "InlineEditableForm",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "BulkEditForm",
    "category": "Forms and inputs",
    "family": "form",
    "required": true
  },
  {
    "id": "SimpleTable",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "DataGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "VirtualizedGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "EditableGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "InlineEditGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "ServerSideGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "InfiniteGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "GroupedGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "TreeGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "PivotGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "CrossTabGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "MasterDetailGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "NestedGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "ComparisonGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "DiffGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "MatrixGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "PropertyGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "LogGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "EventGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "MetricGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "SelectableGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "RangeSelectableGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "BulkActionGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "ContextMenuGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "PinnedColumnGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "PinnedRowGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "SummaryRowGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "CalculatedColumnGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "FormulaColumnGrid",
    "category": "Tables and grids",
    "family": "grid",
    "required": true
  },
  {
    "id": "TableWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "BoardWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "DashboardWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "FormWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "DetailWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "MasterDetailWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "SplitViewWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "TimelineWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "GanttWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "CalendarWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "SchedulerWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "KanbanWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "TreeWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "HierarchyWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "DiagramWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "TopologyWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "ProcessFlowWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "MapWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "FloorPlanWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "RackWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "AnalyticalWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "SPCWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "WaferWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "LogWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "IncidentWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "ComparisonWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "InvestigationWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "DocumentationWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "CodeWorkspace",
    "category": "Workspace archetypes",
    "family": "workspace",
    "required": true
  },
  {
    "id": "Line",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "MultiLine",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Area",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "StackedArea",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Bar",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "GroupedBar",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "StackedBar",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "HorizontalBar",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "ComboChart",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Scatter",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Bubble",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "JitterScatter",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Histogram",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "BoxPlot",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Violin",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Beeswarm",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Pie",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Donut",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Pareto",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Waterfall",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Funnel",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Gauge",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Bullet",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "ProgressGauge",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Radar",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Heatmap",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "CalendarHeatmap",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Treemap",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Sunburst",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Sankey",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Chord",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "ParallelCoordinates",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "GraphChart",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "NetworkGraph",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "RangeChart",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "ConfidenceBandChart",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "Sparkline",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "MicroBar",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "MiniTrend",
    "category": "Charts and visualizations",
    "family": "chart",
    "required": true
  },
  {
    "id": "RunChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "XbarRChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "XbarSChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "IndividualsMovingRange",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "PChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "NPChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "CChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "UChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "CUSUMChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "EWMAChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ControlLimitsChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "CapabilityHistogram",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "CpCpkPanel",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "PpPpkPanel",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "DistributionComparison",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "CorrelationMatrix",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ScatterMatrix",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "RegressionPlot",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ResidualPlot",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ParetoDefects",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ProcessWindowChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ToleranceBandChart",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "GoldenSampleComparison",
    "category": "Statistical process engineering",
    "family": "statistical",
    "required": true
  },
  {
    "id": "SimpleTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "VerticalTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "HorizontalTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "EventTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "IncidentTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "StateTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "MilestoneTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "GanttChart",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "DependencyGantt",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "ResourceGantt",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "PortfolioGantt",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "Roadmap",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "ResourceSchedule",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "MachineSchedule",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "PeopleSchedule",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "ShiftSchedule",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "Calendar",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "MonthCalendar",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "WeekCalendar",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "DayCalendar",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "Agenda",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "ResourceCalendar",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "SwimlaneTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "Burndown",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "Burnup",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "CumulativeFlow",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "CapacityTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "UtilizationTimeline",
    "category": "Planning and time",
    "family": "timeline",
    "required": true
  },
  {
    "id": "FlowDiagram",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "DependencyGraph",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "ServiceTopology",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "NetworkTopology",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "ArchitectureDiagram",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "ProcessFlow",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "ManufacturingRoute",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "DAG",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "WorkflowGraph",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "StateMachine",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "DecisionTree",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "OrgChart",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "GenealogyGraph",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "TraceabilityGraph",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "DataLineage",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "MindMap",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "SwimlaneDiagram",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "PortConnectionDiagram",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "NodeEditor",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "EdgeEditor",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "MiniMap",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "ZoomControls",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "FitView",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "SelectionBox",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "MultiSelectCanvas",
    "category": "Diagrams and canvases",
    "family": "diagram",
    "required": true
  },
  {
    "id": "RackElevation",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "CabinetView",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "SlotView",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "EquipmentModuleLayout",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ChamberLayout",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "FloorPlan",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "FabBayLayout",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "GridMap",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ZoneMap",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "GenericSpaceAllocator",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "CoordinateCanvas",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ImageAnnotation",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "RegionAnnotation",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "HotspotOverlay",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "SpatialHeatmap",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "PortMap",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ConnectorMap",
    "category": "Physical and spatial",
    "family": "spatial",
    "required": true
  },
  {
    "id": "WaferMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WaferBinMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "DefectMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "DefectDensityMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WaferSelectionMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WaferComparison",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WaferZoneOverlay",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "EdgeExclusionOverlay",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ReticleFieldOverlay",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "DieGrid",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WaferSlotMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "CarrierSlotMap",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "FOUPView",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "SubstrateTrackingTimeline",
    "category": "Semiconductor wafer and substrate",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "LotTraveler",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "LotGenealogy",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "LotHistory",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ProcessRoute",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ProcessStepTimeline",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WIPByStep",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "WIPHeatmap",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "HoldQueue",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ReworkFlow",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "DispatchQueue",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "CycleTimeChart",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "QueueTimeChart",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "BottleneckView",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ControlJobView",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ProcessJobView",
    "category": "Semiconductor lot and process",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "RecipeEditor",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "RecipeParameterGrid",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "RecipeDiff",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "RecipeVersionHistory",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ProcessWindow",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ParameterLimits",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "GoldenRecipeComparison",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "APCStatus",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "RunToRunAdjustmentHistory",
    "category": "Semiconductor recipes",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "EquipmentStatePanel",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "EquipmentStateTimeline",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ModuleStatePanel",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ChamberStatePanel",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "EquipmentStateStackChart",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "AvailabilityPanel",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "UtilizationPanel",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "MTBF",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "MTTR",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "OEEPanel",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "AlarmConsole",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "AlarmTimeline",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "EquipmentHealthMatrix",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "PMCalendar",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "MaintenanceTimeline",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "EquipmentModuleDiagram",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ChamberMatching",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "ToolComparison",
    "category": "Semiconductor equipment",
    "family": "semiconductor",
    "required": true
  },
  {
    "id": "SPCDashboard",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ControlChartSuite",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "FDCTraceViewer",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "TraceOverlay",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ParameterTrend",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "YieldTrend",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "YieldByLot",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "YieldByTool",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "YieldByRecipe",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "ParetoDefect",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "BinPareto",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "CapabilityAnalysis",
    "category": "Semiconductor analytics",
    "family": "statistical",
    "required": true
  },
  {
    "id": "FabOverview",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "BayMap",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ToolMap",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "CapacityDashboard",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ConstraintDashboard",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "WIPDashboard",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ProductionFlow",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "ShiftDashboard",
    "category": "Semiconductor factory",
    "family": "spatial",
    "required": true
  },
  {
    "id": "Backlog",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "IssueTable",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "KanbanBoard",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "SprintBoard",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "SprintOverview",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "Milestones",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "ReleasePlan",
    "category": "Software planning",
    "family": "software",
    "required": true
  },
  {
    "id": "RepositoryTree",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "FileTree",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "CodeViewer",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "DiffViewer",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "SplitDiff",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "UnifiedDiff",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "JSONViewer",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "YAMLViewer",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "MarkdownViewer",
    "category": "Software code and documentation",
    "family": "editor",
    "required": true
  },
  {
    "id": "PipelineGraph",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "JobGraph",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "BuildTimeline",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "DeploymentTimeline",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "EnvironmentMatrix",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "ReleaseDashboard",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "ArtifactBrowser",
    "category": "Software delivery",
    "family": "software",
    "required": true
  },
  {
    "id": "MetricsExplorer",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "LogExplorer",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "TraceExplorer",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "TraceWaterfall",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "IncidentCommandCenter",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "AlertConsole",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "SLODashboard",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "ErrorBudget",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "OnCallSchedule",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "RunbookViewer",
    "category": "Software operations",
    "family": "software",
    "required": true
  },
  {
    "id": "APIExplorer",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "RequestBuilder",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "ResponseViewer",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "WebhookInspector",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "EventViewer",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "QueueInspector",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "JobScheduler",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "FeatureFlagConsole",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "ConfigurationViewer",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "ConfigurationDiff",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "AuditViewer",
    "category": "Software platform and integrations",
    "family": "service",
    "required": true
  },
  {
    "id": "PlainTextEditor",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "StreamingLogViewer",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "TerminalOutput",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "FileBrowser",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "DirectoryTree",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "AttachmentGallery",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "ImageViewer",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "ImageAnnotator",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "DocumentMetadata",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "PropertyInspector",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "SchemaViewer",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "APIResponseInspector",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "ObjectInspector",
    "category": "Editors and documents",
    "family": "editor",
    "required": true
  },
  {
    "id": "Comments",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "ThreadedComments",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Mentions",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "ActivityFeed",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "AuditTimeline",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "ApprovalPanel",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "ApprovalFlow",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Assignment",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "OwnerPicker",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "TeamPicker",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Watchers",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Followers",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Labels",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Checklist",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "TaskList",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "StatusTransition",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "WorkflowStepper",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Escalation",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "NotificationPreferences",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "Presence",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "ConflictResolution",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "RevisionHistory",
    "category": "Collaboration and workflow",
    "family": "collaboration",
    "required": true
  },
  {
    "id": "UserDirectory",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "MemberTable",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "RoleManager",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "PermissionMatrix",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "TenantSelector",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "TenantAdministration",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "FeatureFlagManager",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "Settings",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "Preferences",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "ThemeSettings",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "AuditConsole",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "HealthDashboard",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "RuntimeDiagnostics",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "StorageDiagnostics",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "APIConnectivity",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "EnvironmentInfo",
    "category": "Administration",
    "family": "admin",
    "required": true
  },
  {
    "id": "AppShell",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "SidebarShell",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "TopNavShell",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "DualSidebarShell",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "HeaderContent",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "HeaderToolbarContent",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "SingleColumn",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "TwoColumn",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "ThreeColumn",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "DashboardGrid",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "MasterDetail",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "SplitHorizontal",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "SplitVertical",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "ResizableSplit",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "InspectorLayout",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "StickyHeader",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "StickyFooter",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "StickySidebar",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "FullHeightWorkspace",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "CanvasWorkspace",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "DenseOperationsWorkspace",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "CenteredForm",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "DossierLayout",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "ResponsiveCards",
    "category": "Layouts",
    "family": "layout",
    "required": true
  },
  {
    "id": "AccessKeyIdentity",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "TenantIsolation",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "Authorization",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "ServerPagination",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "GeneratedAPIContracts",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "Transactions",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "MigrationHistory",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "ConfigDatabaseMigrations",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "AttachmentsProtection",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "Idempotency",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "OptimisticConcurrency",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "AuditPersistence",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "BackupManifest",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "IsolatedRestore",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "MigrationRehearsal",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "DirectDatabaseSDK",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "ImportPreview",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "CSVExchange",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "XLSXExchange",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "RevisionRevert",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "SavedViewsPersistence",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "DurableJobs",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "WebhooksOutbound",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "WebhooksInbound",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "RealtimeBus",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "IntegrationCredentials",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "RateLimits",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "HealthReadiness",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "StructuredLogging",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "OTelMetrics",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "OTelTraces",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "NotificationDelivery",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "ApplicationGenerator",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "WorkspaceGenerator",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "UpgradePlanner",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "UpgradeApply",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "UpgradeRollback",
    "category": "Platform services",
    "family": "service",
    "required": true
  },
  {
    "id": "ExperienceLab",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "Storybook",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "ThemeStudio",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "ArchitectureRules",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "DependencyLocks",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "SecretScanning",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "AdvisoryScanning",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "SAST",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "SBOM",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "Provenance",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "CleanMacSetup",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "CorporatePaaSPublish",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "CorporateStorageQualification",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "CorporateIdentityQualification",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "VisualRegression",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "KeyboardRegression",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "AccessibilityAssessment",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "PerformanceBudgets",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "SourceCheckpoints",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "CatalogCompleteness",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "APIContractDrift",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  },
  {
    "id": "DocumentationChecks",
    "category": "Developer and certification",
    "family": "certification",
    "required": true
  }
] as const satisfies readonly CatalogVariant[]
