#!/usr/bin/env python3
"""Generate the public generic catalog manifest from catalog/roadmap.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend/src/platform/catalog/generatedVariants.ts"

FAMILIES = {
    "Typography and content": "content",
    "Controls": "control",
    "Indicators": "indicator",
    "Windows and overlays": "surface",
    "Forms and inputs": "form",
    "Tables and grids": "grid",
    "Workspace archetypes": "workspace",
    "Charts and visualizations": "chart",
    "Statistical process engineering": "statistical",
    "Planning and time": "timeline",
    "Diagrams and canvases": "diagram",
    "Physical and spatial": "spatial",
    "Semiconductor wafer and substrate": "semiconductor",
    "Semiconductor lot and process": "semiconductor",
    "Semiconductor recipes": "semiconductor",
    "Semiconductor equipment": "semiconductor",
    "Semiconductor analytics": "statistical",
    "Semiconductor factory": "spatial",
    "Software planning": "software",
    "Software code and documentation": "editor",
    "Software delivery": "software",
    "Software operations": "software",
    "Software platform and integrations": "service",
    "Editors and documents": "editor",
    "Collaboration and workflow": "collaboration",
    "Administration": "admin",
    "Layouts": "layout",
    "Platform services": "service",
    "Developer and certification": "certification",
}


def render() -> str:
    rows = json.loads((ROOT / "catalog/roadmap.json").read_text())["entries"]
    missing = sorted({row["category"] for row in rows} - set(FAMILIES))
    if missing:
        raise SystemExit("Unmapped catalog categories: " + ", ".join(missing))
    entries = [
        {
            "id": row["id"],
            "category": row["category"],
            "family": FAMILIES[row["category"]],
            "required": bool(row["required"]),
        }
        for row in rows
    ]
    payload = json.dumps(entries, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/generate_catalog_registry.py; do not edit by hand.\n"
        "import type { CatalogVariant } from './variants'\n\n"
        f"export const catalogVariants = {payload} as const satisfies readonly CatalogVariant[]\n"
    )


def main() -> int:
    text = render()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"Generated {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
