#!/usr/bin/env python3
"""Export the actual FastAPI contract and deterministic TypeScript declarations.

Dependency-free for the schema subset used here. Unknown schema constructs fail
closed, rather than silently producing `any`. --check never writes files.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import re
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'backend'))
from app.main import create_app
from app.platform.settings import Settings


def identifier(name: str) -> str:
    return re.sub(r'[^A-Za-z0-9_$]', '', name)


def ts(schema: dict) -> str:
    if not isinstance(schema, dict):
        raise ValueError('Unsupported non-object schema.')
    if '$ref' in schema:
        if not schema['$ref'].startswith('#/components/schemas/'):
            raise ValueError('Only local OpenAPI schema references are supported.')
        return identifier(schema['$ref'].split('/')[-1])
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(v) for v in schema['enum'])
    for key, separator in [('anyOf', ' | '), ('oneOf', ' | '), ('allOf', ' & ')]:
        if key in schema:
            return '(' + separator.join(ts(s) for s in schema[key]) + ')'
    kind = schema.get('type')
    if kind in ('integer', 'number'): return 'number'
    if kind == 'boolean': return 'boolean'
    if kind == 'string': return 'string'
    if kind == 'null': return 'null'
    if kind == 'array':
        if 'prefixItems' in schema: raise ValueError('Tuple schemas need an explicit generator extension.')
        return f'Array<{ts(schema.get("items", {}))}>'
    if kind == 'object' or 'properties' in schema:
        required = schema.get('required', [])
        props = schema.get('properties', {})
        fields = [f'{json.dumps(k)}{"" if k in required else "?"}: {ts(v)}' for k, v in props.items()]
        additional = schema.get('additionalProperties', True)
        if additional is not False:
            fields.append('[key: string]: ' + (ts(additional) if isinstance(additional, dict) else 'unknown'))
        return '{ ' + '; '.join(fields) + ' }'
    if kind is None and set(schema) <= {'title', 'description', 'default', 'examples'}:
        return 'unknown'
    raise ValueError(f'Unsupported schema: {schema}')


def generate() -> dict[Path, str]:
    app = create_app(Settings(environment='test',profile='development'))
    document = app.openapi()
    schemas = document.get('components', {}).get('schemas', {})
    lines = ['// Generated by scripts/generate_contracts.py. Do not edit.',
             '// Dates are ISO-8601 strings; server timestamps use explicit UTC offsets.', '']
    for name, value in sorted(schemas.items()):
        lines.append(f'export type {identifier(name)} = {ts(value)}')
    # Prefer complete serialized/output types for display state. Keep input types separately.
    for name in sorted(schemas):
        if name.endswith('-Output'):
            base = name[:-7]
            if base not in schemas:
                lines.append(f'export type {identifier(base)} = {identifier(name)}')
    operations = {}
    lines += ['', 'export interface OperationInputs {']
    outputs = []
    for path, item in sorted(document['paths'].items()):
        for method, operation in sorted(item.items()):
            if method not in {'get','post','put','delete','patch'}: continue
            op = operation['operationId']
            params = operation.get('parameters', [])
            parts = []
            for location in ('path', 'query'):
                values = [p for p in params if p['in'] == location]
                if values:
                    optional = '' if any(p.get('required') for p in values) else '?'
                    content = '; '.join(f'{json.dumps(p["name"])}{"" if p.get("required") else "?"}: {ts(p["schema"])}' for p in values)
                    parts.append(f'{location}{optional}: {{ {content} }}')
            request = operation.get('requestBody')
            if request:
                body = request['content'].get('application/json', {}).get('schema')
                if body is None: raise ValueError('Non-JSON request needs an explicit transport extension.')
                parts.append(f'body{"" if request.get("required") else "?"}: {ts(body)}')
            lines.append(f'  {json.dumps(op)}: {{ {"; ".join(parts)} }}')
            successful = [(status, result) for status, result in operation['responses'].items() if status.startswith('2')]
            variants = []
            for status, result in successful:
                if status == '204': variants.append('void');continue
                value = result.get('content', {}).get('application/json', {}).get('schema')
                variants.append(ts(value) if value is not None else 'unknown')
            outputs.append(f'  {json.dumps(op)}: {" | ".join(dict.fromkeys(variants)) or "unknown"}')
            operations[op] = {'method': method.upper(), 'path': path}
    lines += ['}', 'export interface OperationOutputs {', *outputs, '}',
              'export const operationRoutes = ' + json.dumps(operations, indent=2) + ' as const', '']
    return {ROOT/'contracts/openapi.json': json.dumps(document, indent=2, sort_keys=True)+'\n',
            ROOT/'frontend/src/generated/schema.ts': '\n'.join(lines)}


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    failed=[]
    for path, content in generate().items():
        if args.check:
            if not path.is_file() or path.read_text()!=content: failed.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    if failed: raise SystemExit('Contract drift: '+', '.join(failed))
    print('Contract check passed.' if args.check else 'OpenAPI and TypeScript contracts generated.')
if __name__=='__main__':main()
