export interface WaferCell {x:number;y:number;bin:string;value?:number;defect?:string}
export function waferCells(raw:unknown,rows:number,cols:number):WaferCell[]{if(!raw||typeof raw!=='object'||Array.isArray(raw))return[];const cells=(raw as {cells?:unknown}).cells;if(!Array.isArray(cells))return[];const seen=new Set<string>();return cells.flatMap(value=>{if(!value||typeof value!=='object'||Array.isArray(value))return[];const cell=value as Record<string,unknown>,x=Number(cell.x),y=Number(cell.y),bin=String(cell.bin??'').trim(),key=`${x}:${y}`;if(!Number.isInteger(x)||!Number.isInteger(y)||x<0||y<0||x>=cols||y>=rows||!bin||seen.has(key))return[];seen.add(key);const result:WaferCell={x,y,bin};if(typeof cell.value==='number'&&Number.isFinite(cell.value))result.value=cell.value;if(typeof cell.defect==='string'&&cell.defect.trim())result.defect=cell.defect.trim();return[result]})}
export function waferGoodBins(raw:unknown):Set<string>{if(!raw||typeof raw!=='object'||Array.isArray(raw))return new Set(['GOOD','PASS','1']);const good=(raw as {good_bins?:unknown}).good_bins;return new Set((Array.isArray(good)?good:['GOOD','PASS','1']).filter((value):value is string=>typeof value==='string').map(value=>value.toUpperCase()))}
export function recipeDiff(left:Record<string,unknown>,right:Record<string,unknown>){return [...new Set([...Object.keys(left),...Object.keys(right)])].sort().flatMap(key=>Object.is(left[key],right[key])?[]:[{key,before:left[key],after:right[key]}])}
export function utilization<T extends {state:string;duration:number}>(rows:T[]){const totals=new Map<string,number>();let total=0;for(const row of rows){const duration=Math.max(0,Number(row.duration)||0);total+=duration;totals.set(row.state,(totals.get(row.state)??0)+duration)}return [...totals.entries()].sort((a,b)=>b[1]-a[1]).map(([state,duration])=>({state,duration,percent:total?duration/total*100:0}))}
export function waferDefectSummary(cells:WaferCell[],rows:number,cols:number,goodBins=['GOOD','PASS','1'],edgeExclusion=0){if(rows<1||cols<1||edgeExclusion<0||edgeExclusion*2>=Math.min(rows,cols))throw new Error('Wafer dimensions and edge exclusion are invalid.');const good=new Set(goodBins.map(value=>value.toUpperCase())),bins=new Map<string,number>(),zones={edge:0,center:0},defectsByZone={edge:0,center:0},defectsByBin=new Map<string,number>();for(const cell of cells){const zone=cell.x<edgeExclusion||cell.y<edgeExclusion||cell.x>=cols-edgeExclusion||cell.y>=rows-edgeExclusion?'edge':'center',bin=cell.bin.toUpperCase();bins.set(bin,(bins.get(bin)??0)+1);zones[zone]++;if(!good.has(bin)){defectsByZone[zone]++;defectsByBin.set(bin,(defectsByBin.get(bin)??0)+1)}}const total=cells.length,goodDie=cells.filter(cell=>good.has(cell.bin.toUpperCase())).length;return{totalDie:total,goodDie,defectCount:total-goodDie,yieldPercent:total?goodDie/total*100:0,bins:Object.fromEntries(bins),defectsByZone,defectsByBin:Object.fromEntries(defectsByBin),testedZones:zones}}
export function routeMetrics(steps:Array<Record<string,unknown>>,startedAt?:string,now=new Date()){const completed=steps.filter(step=>['done','complete','completed','passed'].includes(String(step.status??'').toLowerCase())).length,current=steps.find(step=>['running','hold','held','in_progress'].includes(String(step.status??'').toLowerCase())),queueMinutes=steps.reduce((sum,step)=>sum+Math.max(0,Number(step.queue_minutes)||0),0),cycleMinutes=startedAt?Math.max(0,now.getTime()-Date.parse(startedAt))/60000:0;return{stepCount:steps.length,completedSteps:completed,progressPercent:steps.length?completed/steps.length*100:0,currentStep:current?String(current.name??''):null,onHold:Boolean(current&&['hold','held'].includes(String(current.status??'').toLowerCase())),queueMinutes,cycleMinutes,wip:Boolean(steps.length&&completed<steps.length)}}
export function equipmentMetrics(rows:Array<{state:string;duration:number}>,plannedMinutes?:number){const total=rows.reduce((sum,row)=>sum+Math.max(0,row.duration||0),0),production=rows.filter(row=>['production','run','running'].includes(row.state.toLowerCase())).reduce((sum,row)=>sum+Math.max(0,row.duration||0),0),downtime=rows.filter(row=>['unscheduled_down','failure','down'].includes(row.state.toLowerCase())).reduce((sum,row)=>sum+Math.max(0,row.duration||0),0),failures=rows.filter(row=>['unscheduled_down','failure','down'].includes(row.state.toLowerCase())).length;return{totalMinutes:total,productionMinutes:production,downtimeMinutes:downtime,availability:production/(plannedMinutes||total||1),mtbfMinutes:failures?production/failures:null,mttrMinutes:failures?downtime/failures:null}}
export function capacityMetrics(demandUnits:number,capacityUnits:number,shifts=1){if(demandUnits<0||capacityUnits<=0||shifts<1)throw new Error('Capacity inputs are invalid.');const capacity=capacityUnits*shifts;return{demandUnits,capacityUnits:capacity,utilizationPercent:demandUnits/capacity*100,shortfallUnits:Math.max(0,demandUnits-capacity),bottleneck:demandUnits>capacity}}
