import { useState } from 'react'
import type { BaseRecord,ProjectionProps } from '../../platform/workspace/types'
import { ProjectionWorkspaceFrame } from '../../platform/workspace/ProjectionWorkspaceFrame'
import { recordValue } from '../../platform/workspace/projectionUtils'
import { recipeDiff } from './model'
function text(row:BaseRecord,key:string){const value=recordValue(row,key);return value==null?'':String(value)}
function object(row:BaseRecord,key:string):Record<string,unknown>{const value=recordValue(row,key);return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function shown(value:unknown){return value===undefined?'—':typeof value==='object'?JSON.stringify(value):String(value)}
export function RecipeWorkspace<T extends BaseRecord>(props:ProjectionProps<T>){const[selected,setSelected]=useState<string|null>(null),[compare,setCompare]=useState<string>('');return <ProjectionWorkspaceFrame {...props} projectionKey="recipe" title="Recipe compare" description="Versioned structured process recipes with parameter/limit comparison and canonical wafer-run relationships." extraMetrics={rows=>[{label:'Recipes',value:rows.length},{label:'Released',value:rows.filter(row=>text(row,'status')==='released').length}]}>{(rows,{openRow,peekRow})=>{const current=rows.find(row=>row.id===selected)??rows[0],other=rows.find(row=>row.id===compare),parameterDiff=current&&other?recipeDiff(object(current,'parameters'),object(other,'parameters')):[],limitDiff=current&&other?recipeDiff(object(current,'limits'),object(other,'limits')):[];return <div className="recipe-workbench"><nav className="recipe-list">{rows.map(row=><button key={row.id} className={row.id===current?.id?'selected':''} onClick={()=>setSelected(row.id)}><strong>{text(row,'name')}</strong><span>{text(row,'version_name')} · {text(row,'status')}</span><small>{text(row,'process')}</small></button>)}</nav>{current&&<main className="recipe-main"><header><div><span className="eyebrow">{text(current,'process')} · {text(current,'status')}</span><h1>{text(current,'name')} <small>{text(current,'version_name')}</small></h1></div><div className="toolbar-actions"><button onClick={()=>peekRow(current)}>Quick look</button><button className="primary" onClick={()=>openRow(current)}>Dossier</button></div></header><label>Compare with<select value={compare} onChange={event=>setCompare(event.target.value)}><option value="">Select another recipe</option>{rows.filter(row=>row.id!==current.id).map(row=><option key={row.id} value={row.id}>{text(row,'name')} {text(row,'version_name')}</option>)}</select></label><div className="recipe-columns"><section><h3>Parameters</h3>{Object.entries(object(current,'parameters')).map(([key,value])=><div key={key}><span>{key}</span><strong>{shown(value)}</strong></div>)}</section><section><h3>Limits</h3>{Object.entries(object(current,'limits')).map(([key,value])=><div key={key}><span>{key}</span><strong>{shown(value)}</strong></div>)}</section></div>{other&&<section className="recipe-diff"><h3>Differences vs {text(other,'version_name')}</h3>{[...parameterDiff.map(row=>({...row,group:'Parameter'})),...limitDiff.map(row=>({...row,group:'Limit'}))].map(row=><article key={`${row.group}:${row.key}`}><b>{row.group}</b><strong>{row.key}</strong><span>{shown(row.before)}</span><i>→</i><span>{shown(row.after)}</span></article>)}{!parameterDiff.length&&!limitDiff.length&&<p className="muted">No structured differences.</p>}</section>}</main>}</div>}}</ProjectionWorkspaceFrame>}
