import { useState } from 'react'
import type { BaseRecord,ProjectionProps } from '../../platform/workspace/types'
import { ProjectionWorkspaceFrame } from '../../platform/workspace/ProjectionWorkspaceFrame'
import { recordValue } from '../../platform/workspace/projectionUtils'
import { ReadOnlyCodeViewer } from '../../platform/workspace/ReadOnlyCodeViewer'
import { pipelineStages } from './model'
import { customProjectionFieldDisplayText } from '../../platform/workspace/FieldValue'
function text(row:BaseRecord,key:string){const value=recordValue(row,key);return value==null?'':String(value)}
function objectValue(row:BaseRecord,key:string):Record<string,unknown>{const value=recordValue(row,key);return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>: {}}
export function DeliveryWorkspace<T extends BaseRecord>(props:ProjectionProps<T>){const[selected,setSelected]=useState<string|null>(null),display=(row:BaseRecord,key:string)=>customProjectionFieldDisplayText(props.adapter.definition,key,recordValue(row,key));return <ProjectionWorkspaceFrame {...props} projectionKey="pipeline" title="Delivery pipeline" description="CI/CD runs with stage progression, commit/environment context, artifacts, rollback context and canonical service relationships." extraMetrics={rows=>[{label:'Running',value:rows.filter(row=>text(row,'status')==='running').length},{label:'Failed',value:rows.filter(row=>text(row,'status')==='failed').length}]}>{(rows,{openRow,peekRow})=>{const current=rows.find(row=>row.id===selected)??rows[0];return <div className="delivery-workbench"><nav className="delivery-list">{rows.map(row=><button key={row.id} className={current?.id===row.id?'selected':''} onClick={()=>setSelected(row.id)}><strong>{text(row,'run_id')}</strong><span>{text(row,'branch')} · {display(row,'environment')}</span><b className={text(row,'status')}>{display(row,'status')}</b></button>)}</nav>{current&&<main className="delivery-main"><header><div><span className="eyebrow">{display(current,'environment')} · {text(current,'branch')}</span><h1>{text(current,'run_id')}</h1><p>{text(current,'commit_sha')||'No commit'} · {display(current,'duration_minutes')}</p></div><div className="toolbar-actions"><button onClick={()=>peekRow(current)}>Quick look</button><button className="primary" onClick={()=>openRow(current)}>Open run</button></div></header><section className="pipeline-stage-row">{pipelineStages(recordValue(current,'stages')).map((stage,index)=><article key={stage.id} className={stage.status}><i>{index+1}</i><strong>{stage.name}</strong><span>{stage.status}</span><small>{stage.durationSeconds==null?'—':`${stage.durationSeconds}s`}</small>{stage.message&&<p>{stage.message}</p>}</article>)}</section><ReadOnlyCodeViewer value={objectValue(current,'artifacts')} format="json" title="Artifacts & rollback context"/></main>}</div>}}</ProjectionWorkspaceFrame>}
