export interface DescriptiveStats {count:number;mean:number;minimum:number;maximum:number;range:number;sampleStd:number}
export interface ImrStats {center:number;lowerControl:number;upperControl:number;movingRanges:number[];movingRangeCenter:number;movingRangeLower:number;movingRangeUpper:number;sigmaWithin:number;outOfControlIndexes:number[]}
export interface CapabilityStats {mean:number;withinSigma:number;overallSigma:number;cp:number|null;cpk:number|null;pp:number|null;ppk:number|null}
const D2=1.128
const D4=3.267
const XBAR_R:Record<number,[number,number,number]>={2:[1.880,0,3.267],3:[1.023,0,2.574],4:[.729,0,2.282],5:[.577,0,2.114],6:[.483,0,2.004],7:[.419,.076,1.924],8:[.373,.136,1.864],9:[.337,.184,1.816],10:[.308,.223,1.777]}
function values(input:number[]):number[]{if(!input.length)throw new Error('At least one value is required.');if(input.some(value=>!Number.isFinite(value)))throw new Error('Analysis values must be finite numbers.');return [...input]}
function mean(input:number[]):number{return input.reduce((total,value)=>total+value,0)/input.length}
function sampleStd(input:number[]):number{if(input.length<2)return 0;const m=mean(input);return Math.sqrt(input.reduce((total,value)=>total+(value-m)**2,0)/(input.length-1))}
export function descriptive(input:number[]):DescriptiveStats{const xs=values(input),m=mean(xs),minimum=Math.min(...xs),maximum=Math.max(...xs);return{count:xs.length,mean:m,minimum,maximum,range:maximum-minimum,sampleStd:sampleStd(xs)}}
export function imr(input:number[]):ImrStats{const xs=values(input),center=mean(xs),movingRanges=xs.slice(1).map((value,index)=>Math.abs(value-xs[index]!)),movingRangeCenter=movingRanges.length?mean(movingRanges):0,sigmaWithin=movingRangeCenter?movingRangeCenter/D2:0,spread=3*sigmaWithin,lowerControl=center-spread,upperControl=center+spread;return{center,lowerControl,upperControl,movingRanges,movingRangeCenter,movingRangeLower:0,movingRangeUpper:movingRangeCenter*D4,sigmaWithin,outOfControlIndexes:xs.flatMap((value,index)=>value<lowerControl||value>upperControl?[index]:[])}}
export function xbarR(groups:number[][]){if(groups.length<2)throw new Error('At least two subgroups are required.');const normalized=groups.map(values),first=normalized[0]!;const size=first.length,constants=XBAR_R[size];if(!constants||normalized.some(group=>group.length!==size))throw new Error('Xbar-R requires equal subgroup sizes from 2 through 10.');const means=normalized.map(mean),ranges=normalized.map(group=>Math.max(...group)-Math.min(...group)),grandMean=mean(means),rangeCenter=mean(ranges),[a2,d3,d4]=constants,xbarLower=grandMean-a2*rangeCenter,xbarUpper=grandMean+a2*rangeCenter,rangeLower=d3*rangeCenter,rangeUpper=d4*rangeCenter;return{subgroupSize:size,means,ranges,xbarCenter:grandMean,xbarLower,xbarUpper,rangeCenter,rangeLower,rangeUpper,outOfControlMeanIndexes:means.flatMap((value,index)=>value<xbarLower||value>xbarUpper?[index]:[]),outOfControlRangeIndexes:ranges.flatMap((value,index)=>value<rangeLower||value>rangeUpper?[index]:[])}}
export function capability(input:number[],lowerSpec?:number|null,upperSpec?:number|null):CapabilityStats{const xs=values(input);if(lowerSpec==null&&upperSpec==null)throw new Error('At least one specification limit is required.');if(lowerSpec!=null&&upperSpec!=null&&lowerSpec>=upperSpec)throw new Error('Lower specification limit must be below upper specification limit.');const m=mean(xs),within=imr(xs).sigmaWithin,overall=sampleStd(xs);const indices=(sigma:number):[number|null,number|null]=>{if(sigma<=0)return[null,null];const lower=lowerSpec!=null?(m-lowerSpec)/(3*sigma):null,upper=upperSpec!=null?(upperSpec-m)/(3*sigma):null,candidates=[lower,upper].filter((value):value is number=>value!=null),centered=lowerSpec!=null&&upperSpec!=null?(upperSpec-lowerSpec)/(6*sigma):null;return[centered,candidates.length?Math.min(...candidates):null]};const[cp,cpk]=indices(within),[pp,ppk]=indices(overall);return{mean:m,withinSigma:within,overallSigma:overall,cp,cpk,pp,ppk}}
export function ewma(input:number[],alpha=.2,target?:number):number[]{const xs=values(input);if(!(alpha>0&&alpha<=1))throw new Error('EWMA alpha must be greater than 0 and at most 1.');let current=target??xs[0]!;if(!Number.isFinite(current))throw new Error('EWMA target must be finite.');return xs.map(value=>(current=alpha*value+(1-alpha)*current))}
export function pareto(categories:string[]){const counts=new Map<string,number>();for(const raw of categories){const key=String(raw).trim()||'Unspecified';counts.set(key,(counts.get(key)??0)+1)}const total=categories.length;if(!total)return[];let running=0;return[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([category,count])=>{running+=count;return{category,count,cumulativePercent:running/total*100}})}
export function runRuleFlags(input:number[],center?:number){const xs=values(input),midpoint=center??mean(xs);if(!Number.isFinite(midpoint))throw new Error('Run-rule center must be finite.');const eightOnOneSide:number[]=[],sixPointTrend:number[]=[];for(let end=7;end<xs.length;end++){const window=xs.slice(end-7,end+1);if(window.every(value=>value>midpoint)||window.every(value=>value<midpoint))eightOnOneSide.push(end)}for(let end=5;end<xs.length;end++){const window=xs.slice(end-5,end+1),increasing=window.slice(1).every((value,index)=>window[index]!<value),decreasing=window.slice(1).every((value,index)=>window[index]!>value);if(increasing||decreasing)sixPointTrend.push(end)}return{eightOnOneSide,sixPointTrend}}
const XBAR_S:Record<number,[number,number,number]>={2:[2.659,0,3.267],3:[1.954,0,2.568],4:[1.628,0,2.266],5:[1.427,0,2.089],6:[1.287,.848,1.996],7:[1.182,.888,1.924],8:[1.099,.902,1.864],9:[1.032,.914,1.816],10:[.975,.921,1.777]}
export function xbarS(groups:number[][]){if(groups.length<2)throw new Error('At least two subgroups are required.');const normalized=groups.map(values),first=normalized[0]!,size=first.length,constants=XBAR_S[size];if(!constants||normalized.some(group=>group.length!==size))throw new Error('Xbar-S requires equal subgroup sizes from 2 through 10.');const means=normalized.map(mean),standardDeviations=normalized.map(sampleStd),xbarCenter=mean(means),sigmaCenter=mean(standardDeviations),[a3,b3,b4]=constants,xbarLower=xbarCenter-a3*sigmaCenter,xbarUpper=xbarCenter+a3*sigmaCenter,sigmaLower=b3*sigmaCenter,sigmaUpper=b4*sigmaCenter;return{subgroupSize:size,means,standardDeviations,xbarCenter,xbarLower,xbarUpper,sigmaCenter,sigmaLower,sigmaUpper,outOfControlMeanIndexes:means.flatMap((value,index)=>value<xbarLower||value>xbarUpper?[index]:[]),outOfControlSigmaIndexes:standardDeviations.flatMap((value,index)=>value<sigmaLower||value>sigmaUpper?[index]:[])}
}
function attribute(defects:number[],samples:number[]){const d=values(defects),n=values(samples);if(d.length!==n.length||d.some((value,index)=>value<0||value>n[index]!||n[index]!<=0))throw new Error('Defects and sample sizes must be aligned and within valid bounds.');return[d,n] as const}
export function pChart(defects:number[],samples:number[]){const[d,n]=attribute(defects,samples),center=d.reduce((a,v)=>a+v,0)/n.reduce((a,v)=>a+v,0),limits=n.map(sample=>3*Math.sqrt(center*(1-center)/sample)),lower=limits.map(limit=>Math.max(0,center-limit)),upper=limits.map(limit=>Math.min(1,center+limit)),proportions=d.map((value,index)=>value/n[index]!);return{proportions,center,lowerControl:lower,upperControl:upper,outOfControlIndexes:proportions.flatMap((value,index)=>value<lower[index]!||value>upper[index]!?[index]:[])}}
export function npChart(defects:number[],sampleSize:number){if(sampleSize<=0)throw new Error('Sample size must be positive.');const[d]=attribute(defects,defects.map(()=>sampleSize)),center=d.reduce((a,v)=>a+v,0)/d.length,pBar=center/sampleSize,spread=3*Math.sqrt(sampleSize*pBar*(1-pBar)),lower=Math.max(0,center-spread),upper=center+spread;return{counts:d,center,lowerControl:lower,upperControl:upper,outOfControlIndexes:d.flatMap((value,index)=>value<lower||value>upper?[index]:[])}}
export function cChart(input:number[]){const xs=values(input),center=mean(xs),spread=3*Math.sqrt(center),lower=Math.max(0,center-spread),upper=center+spread;return{counts:xs,center,lowerControl:lower,upperControl:upper,outOfControlIndexes:xs.flatMap((value,index)=>value<lower||value>upper?[index]:[])}}
export function uChart(defects:number[],units:number[]){const[d,n]=attribute(defects,units),center=d.reduce((a,v)=>a+v,0)/n.reduce((a,v)=>a+v,0),lower=n.map(sample=>Math.max(0,center-3*Math.sqrt(center/sample))),upper=n.map(sample=>center+3*Math.sqrt(center/sample)),rates=d.map((value,index)=>value/n[index]!);return{rates,center,lowerControl:lower,upperControl:upper,outOfControlIndexes:rates.flatMap((value,index)=>value<lower[index]!||value>upper[index]!?[index]:[])}}
export function cusum(input:number[],target?:number,allowance=0,decisionInterval=5){const xs=values(input),midpoint=target??mean(xs);if(!Number.isFinite(midpoint)||allowance<0||decisionInterval<=0)throw new Error('CUSUM target, allowance and decision interval are invalid.');let positiveValue=0,negativeValue=0;const positive:number[]=[],negative:number[]=[];for(const value of xs){positiveValue=Math.max(0,positiveValue+value-midpoint-allowance);negativeValue=Math.min(0,negativeValue+value-midpoint+allowance);positive.push(positiveValue);negative.push(negativeValue)}return{target:midpoint,positive,negative,decisionInterval,positiveSignalIndexes:positive.flatMap((value,index)=>value>decisionInterval?[index]:[]),negativeSignalIndexes:negative.flatMap((value,index)=>value<-decisionInterval?[index]:[])} }
export function correlation(xInput:number[],yInput:number[]){const xs=values(xInput),ys=values(yInput);if(xs.length!==ys.length||xs.length<2)throw new Error('Correlation requires aligned pairs with at least two values.');const xMean=mean(xs),yMean=mean(ys),denominator=Math.sqrt(xs.reduce((total,value)=>total+(value-xMean)**2,0)*ys.reduce((total,value)=>total+(value-yMean)**2,0));if(denominator===0)throw new Error('Correlation is undefined for zero variance.');return xs.reduce((total,value,index)=>total+(value-xMean)*(ys[index]!-yMean),0)/denominator}
export function linearRegression(xInput:number[],yInput:number[]){const xs=values(xInput),ys=values(yInput);if(xs.length!==ys.length||xs.length<2)throw new Error('Regression requires aligned pairs with at least two values.');const xMean=mean(xs),yMean=mean(ys),denominator=xs.reduce((total,value)=>total+(value-xMean)**2,0);if(denominator===0)throw new Error('Regression is undefined for zero x variance.');const slope=xs.reduce((total,value,index)=>total+(value-xMean)*(ys[index]!-yMean),0)/denominator,intercept=yMean-slope*xMean,predictions=xs.map(value=>intercept+slope*value),total=ys.reduce((sum,value)=>sum+(value-yMean)**2,0),residual=ys.reduce((sum,value,index)=>sum+(value-predictions[index]!)**2,0);return{slope,intercept,rSquared:total===0&&residual===0?1:total?1-residual/total:0}}
